"""The `cp` CLI — entry point for tenant operations.

Subcommands per spec v02 §2.1:
  cp init     → walk through populating .cp-engine.local.toml
  cp sync     → run one sync cycle locally (same logic as the Action)
  cp render   → re-render generated files (master-cp.md, CLAUDE.md)
  cp status   → show what would change without writing
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

import click

from cp_engine.config import ConfigError, load
from cp_engine.config import CommittedConfigMissing
from cp_engine.init import InitAborted, run_init
from cp_engine.sync import SyncError, sync_tenant


@click.group()
@click.version_option(package_name="cp-engine")
def main() -> None:
    """Context Protocol Engine — tenant operations."""


@main.command()
@click.option(
    "--non-interactive",
    is_flag=True,
    help="Don't prompt; mark every committed project as skipped (useful in CI).",
)
def init(non_interactive: bool) -> None:
    """Walk through populating .cp-engine.local.toml interactively."""
    try:
        run_init(Path.cwd(), interactive=not non_interactive)
    except CommittedConfigMissing as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)
    except InitAborted as exc:
        click.echo(str(exc), err=True)
        sys.exit(1)
    except KeyboardInterrupt:
        click.echo("\nAborted. Partial progress (if any) has been saved.", err=True)
        sys.exit(130)


@main.command()
def sync() -> None:
    """Run one sync cycle for the current tenant."""
    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    try:
        result = sync_tenant(config)
    except SyncError as exc:
        click.echo(f"Sync failed: {exc}", err=True)
        sys.exit(1)

    if result.no_op:
        click.echo(f"No changes ({result.projects_seen} projects checked).")
        return

    click.echo(f"Synced {result.projects_seen} projects.")
    for path in result.files_written:
        click.echo(f"  wrote    {path.relative_to(config.root)}")
    for path in result.files_deactivated:
        click.echo(f"  deactivated {path.relative_to(config.root)}")


@main.command()
def render() -> None:
    """Re-render generated files (alias for `cp sync` in v0.1)."""
    # In v0.1 there's no separate render-only path — sync already writes
    # only when content changed and never reaches out to the database
    # for unchanged regions. Future: a true `--no-network` render that
    # uses cached project state.
    click.echo("`cp render` is currently an alias for `cp sync`. Running sync…")
    ctx = click.get_current_context()
    ctx.invoke(sync)


@main.command(name="refresh-pristine")
@click.option(
    "--dry-run",
    is_flag=True,
    help="Show what would be refreshed without writing.",
)
def refresh_pristine(dry_run: bool) -> None:
    """Re-scaffold project CPs that have no hand-written content.

    A project CP is "pristine" if it still contains the placeholder text
    that the scaffold inserted ("<one-line description of what this
    project is and who it's for>"). Pristine CPs were generated by an
    older engine version and have outdated provenance, missing
    metadata blocks, or wrong section structures (e.g. v0.1 templates
    didn't have project-facts; v0.2 templates do).

    Edited CPs (the placeholder is gone or any other section was filled
    in) are NEVER touched — that's hand-written content the engine has
    no business overwriting.

    Use this once after upgrading cp-engine versions to refresh the
    template shape across the tenant.
    """
    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    from cp_engine.refresh import refresh_pristine_cps

    try:
        result = refresh_pristine_cps(config, dry_run=dry_run)
    except SyncError as exc:
        click.echo(f"Refresh failed: {exc}", err=True)
        sys.exit(1)

    if not result.pristine_files:
        click.echo("No pristine project CPs found. Nothing to refresh.")
        return

    if dry_run:
        click.echo(f"Would refresh {len(result.pristine_files)} pristine project CP(s):")
    else:
        click.echo(f"Refreshed {len(result.pristine_files)} pristine project CP(s):")
    for path in result.pristine_files:
        click.echo(f"  {path.relative_to(config.root)}")
    if result.skipped_files:
        click.echo(f"\nSkipped {len(result.skipped_files)} edited CP(s) (hand-written content preserved).")


@main.command(name="migrate-to-v03")
@click.option(
    "--dry-run",
    is_flag=True,
    help="Show what would move without touching the disk.",
)
def migrate_to_v03(dry_run: bool) -> None:
    """One-shot move of v0.2's flat `projects/<code>.md` layout to v0.3's
    per-project working dirs at `<scope>/projects/<code>/cp.md`.

    Uses `git mv` to preserve rename detection. Refuses to run on a dirty
    working tree — commit or stash first. After this runs cleanly, regular
    `cp sync` keeps using the new layout."""
    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    from cp_engine.migrate import MigrationError, migrate_to_v03 as _run

    try:
        result = _run(config, dry_run=dry_run)
    except MigrationError as exc:
        click.echo(f"Migration aborted: {exc}", err=True)
        sys.exit(1)
    except SyncError as exc:
        click.echo(f"Migration aborted: {exc}", err=True)
        sys.exit(1)

    label = "Would move" if dry_run else "Moved"
    if not result.moved and not result.skipped:
        click.echo("Nothing to migrate — no v0.2 layout files found.")
        return

    click.echo(f"{label} {len(result.moved)} file(s):")
    for src, dst in result.moved:
        click.echo(f"  {src.relative_to(config.root)} → {dst.relative_to(config.root)}")
    if result.skipped:
        click.echo(f"\nSkipped {len(result.skipped)} file(s) — resolve by hand:")
        for src, reason in result.skipped:
            click.echo(f"  {src.relative_to(config.root)}: {reason}")

    if not dry_run:
        click.echo(
            "\nReview the changes, then commit:\n"
            "  git status\n"
            '  git commit -m "cp-engine v0.3: restructure to per-project working directories"'
        )


@main.command(name="capture-session")
@click.option(
    "--source-repo",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help="Source repo path (a code repo with a .cp-link). Mutually exclusive with --working-dir.",
)
@click.option(
    "--working-dir",
    "working_dir",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help=(
        "cp working-dir path (for content-only projects with no separate "
        "source repo). Mutually exclusive with --source-repo. The cp tenant "
        "root is found by walking up for .cp-engine.toml, so --cp-tenant "
        "isn't needed."
    ),
)
@click.option(
    "--summary-file",
    "summary_file",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    required=True,
    help="Path to a file containing the session summary (Claude writes this).",
)
@click.option(
    "--user",
    required=True,
    help="Display name for the session author (e.g. \"Drew\").",
)
@click.option(
    "--cp-tenant",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help="Path to the cp tenant clone. Required for unlinked source repos.",
)
@click.option("--no-commit", is_flag=True, help="Don't run git add/commit/push.")
@click.option("--no-push", is_flag=True, help="Commit but don't push.")
def capture_session_cmd(
    source_repo: Path | None,
    working_dir: Path | None,
    summary_file: Path,
    user: str,
    cp_tenant: Path | None,
    no_commit: bool,
    no_push: bool,
) -> None:
    """Write a session summary back to the cp tree.

    Two modes:

    \b
    --source-repo <path>  (default: cwd)
        For source-code repos with a .cp-link. Resolves destination via
        the link (self-healing if stale), or falls back to
        <cp-tenant>/exceptions/ for untracked repos.

    --working-dir <path>
        For content-only projects (1P engagements without a code repo).
        Skips source-repo resolution; writes directly to <path>/sessions/.
        The cp tenant root is found by walking up for .cp-engine.toml.

    Both modes write `<wd>/sessions/<YYYY-MM-DD>-<HHMM>-<user>.md`,
    update the project's `cp.md` Last session line, and commit + push.
    """
    from cp_engine.capture_session import (
        CaptureSessionError,
        capture_session,
        capture_session_in_working_dir,
    )

    if source_repo is not None and working_dir is not None:
        click.echo(
            "Error: pass --source-repo or --working-dir, not both.", err=True
        )
        sys.exit(2)

    summary_text = summary_file.read_text(encoding="utf-8")

    try:
        if working_dir is not None:
            result = capture_session_in_working_dir(
                working_dir=working_dir,
                summary_text=summary_text,
                user=user,
                commit=not no_commit,
                push=not (no_commit or no_push),
            )
        else:
            repo = (source_repo or Path.cwd()).resolve()
            result = capture_session(
                source_repo=repo,
                summary_text=summary_text,
                user=user,
                cp_tenant=cp_tenant,
                commit=not no_commit,
                push=not (no_commit or no_push),
            )
    except CaptureSessionError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(1)

    if result.is_exception:
        click.echo(
            f"Logged exception (repo not tracked in this cp tenant): "
            f"{result.summary_path}"
        )
    else:
        click.echo(f"Wrote session summary: {result.summary_path}")
        if result.cp_md_updated:
            click.echo("Updated cp.md Last session line.")
        if result.extra_files_committed:
            click.echo(
                f"Also committed {len(result.extra_files_committed)} other file(s) "
                f"in the working dir (binaries excluded by .gitignore):"
            )
            wd = result.cp_working_dir
            for p in result.extra_files_committed:
                rel = p.relative_to(wd) if wd else p
                click.echo(f"  {rel}")
    if result.commit_sha:
        # Distinguish actually-skipped (--no-push or --no-commit) from
        # actually-pushed from rebased-then-pushed. Push *failures* now
        # raise PushFailed and are surfaced via the CaptureSessionError
        # branch above, so reaching here with pushed=False means the
        # caller asked us not to push.
        if result.push_rebased:
            click.echo(
                f"Committed {result.commit_sha}, rebased on top of upstream, "
                "and pushed."
            )
        elif result.pushed:
            click.echo(f"Committed {result.commit_sha} and pushed.")
        else:
            click.echo(f"Committed {result.commit_sha} (push skipped).")


@main.command(name="project-context")
@click.option(
    "--working-dir",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help="cp working dir. Defaults to cwd.",
)
@click.option("--user", help="Which `[local-repos.<user>]` entry to use.")
@click.option("--days", type=int, default=7, help="Lookback window. Default 7.")
def project_context_cmd(
    working_dir: Path | None,
    user: str | None,
    days: int,
) -> None:
    """Print recent activity for a project: git log + session captures.

    Run from inside a cp working dir. Reads the linked source repo's
    local clone path from `<tenant>/.cp-engine.toml [local-repos.<user>]`,
    runs `git log --since=<days> ago` there, lists session files in the
    working dir's `sessions/` directory from the same window, and prints
    one chronological timeline.
    """
    from cp_engine.project_context import ProjectContextError, project_context

    wd = (working_dir or Path.cwd()).resolve()
    try:
        result = project_context(working_dir=wd, user=user, days=days)
    except ProjectContextError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(1)

    click.echo(f"# {result.repo_name} — last {result.window_days} days")
    if result.github_url:
        click.echo(f"GitHub: {result.github_url}")
    click.echo(f"Local clone: {result.local_clone or '(not on this machine)'}")
    click.echo()

    if not result.commits and not result.sessions:
        click.echo("(no activity in window)")
        return

    # Merge commits + sessions on one timeline. Each entry has a `.when`
    # attribute; sort newest first.
    timeline: list[tuple[datetime, str]] = []
    for c in result.commits:
        line = (
            f"  {c.when.strftime('%Y-%m-%d %H:%M')}  commit {c.sha}  "
            f"({c.author}) {c.subject}"
        )
        timeline.append((c.when, line))
    for s in result.sessions:
        one = s.one_liner or "(no summary)"
        line = (
            f"  {s.when.strftime('%Y-%m-%d %H:%M')}  session         "
            f"({s.user}) {one}"
        )
        timeline.append((s.when, line))
    timeline.sort(key=lambda t: t[0], reverse=True)
    for _when, line in timeline:
        click.echo(line)
    click.echo()
    click.echo(f"({len(result.commits)} commits, {len(result.sessions)} sessions)")


@main.command(name="link-local")
def link_local_cmd() -> None:
    """Wire `.cp-link` files into each source repo named in `[local-repos]`.

    Reads `.cp-engine.local.toml`'s `[local-repos]` table, validates each
    path is a git repo whose remote matches the entry, finds the
    corresponding cp working dir by walking the cp tenant tree, and writes
    `<source-repo>/.cp-link` containing the absolute path of that working
    dir. Also adds `.cp-link` to `.git/info/exclude` so the source repo
    won't accidentally commit it.

    Idempotent — re-running with no changes is a no-op.
    """
    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    from cp_engine.link_local import LinkLocalError, link_local as _run

    if not config.local_repos:
        click.echo(
            "No [local-repos] entries in .cp-engine.local.toml. Add one per "
            "repo you want linked, e.g.:\n\n"
            "  [local-repos]\n"
            '  "mc-2"      = "/Users/you/Documents/Python/mc-2"\n'
            '  "cp-engine" = "/Users/you/Documents/Python/context-protocol"\n'
        )
        return

    try:
        results = _run(config)
    except LinkLocalError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(1)

    wrote = sum(1 for r in results if r.wrote_link)
    excluded = sum(1 for r in results if r.excluded)
    for r in results:
        action = "wrote" if r.wrote_link else "ok   "
        click.echo(f"  {action} {r.source_repo_path}/.cp-link → {r.cp_working_dir}")
    click.echo(
        f"\n{len(results)} repo(s) linked. "
        f"{wrote} new/updated link file(s); "
        f"{excluded} .git/info/exclude update(s)."
    )


@main.command()
def status() -> None:
    """Show what would change on next sync (no writes — read-only)."""
    click.echo("cp status — not implemented yet (lands in v0.4)")
    sys.exit(1)


@main.command(name="migrate-projects-flat")
@click.option(
    "--tenant-root",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=None,
    help="Tenant root (default: current directory).",
)
def migrate_projects_flat_cmd(tenant_root: Path | None) -> None:
    """One-shot move of pre-v0.7's `<scope>/projects/<dir>` layout to v0.7's
    `<scope>/<dir>` layout.

    Uses `git mv` to preserve rename detection. Refuses to run on a dirty
    working tree — commit or stash first. Idempotent: re-running on an
    already-migrated tree is a no-op. After this runs cleanly, regular
    `cp sync` keeps using the new layout.

    Also rewrites `.cp-link` files in linked source repos so they point
    at the new working-dir paths."""
    from cp_engine.migrate_flat import MigrateFlatError, migrate_projects_flat

    root = tenant_root or Path.cwd()
    try:
        result = migrate_projects_flat(root)
    except MigrateFlatError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    if result.no_op:
        click.echo("Nothing to migrate (tree already matches v0.7 layout).")
        return

    for src, dst in result.moved_dirs:
        click.echo(f"  moved: {src.relative_to(root)} → {dst.relative_to(root)}")
    for path in result.removed_projects_dirs:
        click.echo(f"  removed empty: {path.relative_to(root)}")
    for path in result.rewrote_cp_links:
        click.echo(f"  rewrote .cp-link: {path}")
    click.echo(
        f"\nDone. Review the staged changes (`git status`) and commit when "
        f"satisfied. Source-repo .cp-link files are not under git control "
        f"so they were updated in place."
    )


@main.command(name="migrate-accounts")
@click.option(
    "--dry-run",
    is_flag=True,
    help="Preview the moves and residue without touching the disk.",
)
def migrate_accounts_cmd(dry_run: bool) -> None:
    """One-shot move of flat `1p/<dir>/` layout to account-nested
    `1p/<company>/<dir>/` layout (Phase 2 of the account restructure).

    Reads MC-2 once to resolve each flat dir's company, `git mv`s into
    `1p/<company-slug>/`, absorbs `_teleflex.md` (if present) into
    `1p/teleflex/cp.md` under a dated "Legacy notes" heading, then runs
    `cp sync` so account `cp.md` files get scaffolded and master-cp
    re-renders with the new Account column.

    Refuses to run on a dirty working tree. Hard-fails if any flat dir
    can't be matched against MC-2 (fix MC-2 or hand-move the dir, then
    re-run). Idempotent: re-running on an already-migrated tree is a
    no-op.

    Doesn't commit; review with `git status` / `git diff` and commit
    yourself."""
    from cp_engine.migrate_accounts import (
        MigrateAccountsError,
        migrate_accounts,
    )

    root = Path.cwd()
    try:
        result = migrate_accounts(root, dry_run=dry_run)
    except MigrateAccountsError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    if result.unresolved_dirs:
        click.echo(
            f"Cannot proceed: {len(result.unresolved_dirs)} dir(s) under 1p/ "
            f"don't match any MC-2 project.", err=True,
        )
        for path in result.unresolved_dirs:
            click.echo(f"  {path.relative_to(root)}", err=True)
        click.echo(
            "\nFix MC-2 (add the project) or hand-move the dir, then re-run.",
            err=True,
        )
        sys.exit(1)

    if result.no_op:
        click.echo("Nothing to migrate (1p/ already matches account-nested layout).")
        return

    label = "Would move" if dry_run else "Moved"
    click.echo(f"{label} {len(result.planned_moves)} dir(s):")
    for old, new in result.planned_moves:
        click.echo(f"  {old.relative_to(root)} → {new.relative_to(root)}")

    if result.absorbed_teleflex:
        verb = "Would absorb" if dry_run else "Absorbed"
        click.echo(f"\n{verb} _teleflex.md into 1p/teleflex/cp.md.")

    if dry_run:
        click.echo(
            "\nWill run: cp sync (scaffolds account cp.md files, "
            "re-renders master-cp)"
        )
        if result.residue:
            click.echo("\nResidue — these will need hand-fixing post-migration:")
            for hint in result.residue:
                click.echo(f"  {hint}")
        click.echo(
            "\nDry-run — nothing changed. Re-run without --dry-run to execute."
        )
        return

    if result.sync_files_written:
        click.echo(f"\nSync wrote {len(result.sync_files_written)} file(s).")

    if result.residue:
        click.echo("\nResidue — hand-fix these:")
        for hint in result.residue:
            click.echo(f"  {hint}")

    click.echo("\nDone. Review with `git status` / `git diff`, then commit.")


@main.command(name="resolve-engine-pin")
@click.option(
    "--tenant-root",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=None,
    help="Tenant root (default: current directory).",
)
@click.option(
    "--format",
    "output_format",
    type=click.Choice(["tag", "pip-spec", "json"]),
    default="tag",
    help="Output format. tag=v0.6.0; pip-spec=full git+url@tag; json=structured.",
)
def resolve_engine_pin_cmd(tenant_root: Path | None, output_format: str) -> None:
    """Resolve [engine].version constraint to the highest matching git tag.

    Used by the GitHub Actions runner so bumping the tenant pin is
    sufficient to pick up a new engine release — no workflow edit needed.
    """
    from cp_engine.pin_resolver import ENGINE_REPO_URL, PinResolutionError, resolve_for_tenant

    root = tenant_root or Path.cwd()
    try:
        resolution = resolve_for_tenant(root)
    except PinResolutionError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    if output_format == "tag":
        click.echo(resolution.tag)
    elif output_format == "pip-spec":
        click.echo(f"cp-engine @ git+{ENGINE_REPO_URL}@{resolution.tag}")
    else:
        import json

        click.echo(
            json.dumps(
                {
                    "constraint": resolution.constraint,
                    "tag": resolution.tag,
                    "version": str(resolution.version),
                }
            )
        )


@main.command("parse-sprint")
@click.argument("path", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option("--json", "as_json", is_flag=True, help="Emit JSON to stdout.")
def parse_sprint_cmd(path: Path, as_json: bool) -> None:
    """Parse a sprint file and emit its structured representation.

    Without `--json`, prints a one-line summary. With `--json`, emits the
    full `SprintFile` as JSON — useful for piping into `jq` or another
    consumer that wants to introspect a sprint's parsed state.
    """
    from cp_engine.sprints import parse_sprint_file, sprint_file_to_dict

    sf = parse_sprint_file(path)
    if as_json:
        import json

        click.echo(json.dumps(sprint_file_to_dict(sf), default=str, indent=2))
    else:
        click.echo(
            f"{sf.project_code} · {sf.week_iso} · "
            f"{len(sf.client_open_asks)} asks · {len(sf.risks)} risks"
        )


@main.command("parse-transcript")
@click.argument("path", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option(
    "--gap-threshold",
    type=int,
    default=2,
    help="Flag audio gaps >= this many minutes. Default 2.",
)
@click.option(
    "--codes",
    default="",
    help="Comma-separated project codes to scan for. Empty → no code scan.",
)
def parse_transcript_cmd(path: Path, gap_threshold: int, codes: str) -> None:
    """Audit a Fathom-style transcript. Emits JSON to stdout.

    Output schema:
      {speakers, duration_minutes, gaps[], mentioned_codes[], action_items[]}

    Used by /cp-ingest plugin to surface a confirmation prompt before
    writing anything. Catches transcripts with audio gaps, missing speakers,
    or no mentioned project codes — the W19 retro flagged these failure
    modes after several got into committed artifacts.
    """
    import json
    from cp_engine.ingest import parse_transcript

    code_list = tuple(c.strip() for c in codes.split(",") if c.strip())
    audit = parse_transcript(
        path, gap_threshold_minutes=gap_threshold, project_codes=code_list
    )
    click.echo(json.dumps(audit.to_dict(), indent=2))


@main.command("list-active-projects")
@click.option(
    "--scope",
    type=click.Choice(["1p", "fpsf", "canonic", "all"]),
    default="all",
    help="Filter by scope. Default 'all'.",
)
@click.option(
    "--company",
    default=None,
    help="Filter by company code (case-insensitive, e.g. 'GGL' or 'IBX'). "
    "Used by /cp-ingest --account <company> to find the projects a "
    "multi-project account meeting touches. Default: all companies.",
)
def list_active_projects_cmd(scope: str, company: str | None) -> None:
    """List active projects from MC-2 as JSON for transcript classification.

    Output: list of {code, name, company_code, company_name, owner, scope}.
    Used by /cp-ingest plugin to give Claude the candidate-projects list
    when classifying which projects a transcript touches.
    """
    import json
    from cp_engine.state import scope_for
    from cp_engine.status import is_active_status
    from cp_engine.sync import _default_backend_factory

    config = _load_config_or_die()
    backend = _default_backend_factory(config.sync.backend)
    projects = backend.read_projects(config)

    company_lc = company.lower() if company else None

    out = []
    for p in projects:
        if p.source == "engagement":
            if not is_active_status(p.status) or p.is_internal:
                continue
        else:
            if p.status != "Active":
                continue
        proj_scope = scope_for(p.company_kind)
        if scope != "all" and proj_scope != scope:
            continue
        # Phase B.2: --company filter for /cp-ingest --account flow.
        if company_lc and (p.company_code or "").lower() != company_lc:
            continue
        out.append(
            {
                "code": p.code,
                "name": p.name,
                "company_code": p.company_code,
                "company_name": p.company_name,
                "owner": p.owner,
                "scope": proj_scope,
                "source": p.source,
            }
        )
    out.sort(key=lambda r: (r["scope"], r["code"]))
    click.echo(json.dumps(out, indent=2))


@main.command("ingest")
@click.option(
    "--plan",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    required=True,
    help="YAML plan file to execute.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Validate the plan and print what would happen, but don't write files.",
)
def ingest_cmd(plan: Path, dry_run: bool) -> None:
    """Execute an ingest plan against the cp tenant.

    The plan is a YAML file produced by /cp-ingest (or hand-authored).
    Schema: {transcript: ..., projects: {<code>: {<verb>: [items]}}, themes: [...]}

    On success: writes bullets to the right sprint-file subsections; the
    plan is saved (separately, by the plugin) to sprints/<W##>/_ingest-log/
    for audit. Idempotent — re-running the same plan is a no-op via
    content-hash deduplication.
    """
    import json
    import yaml
    from cp_engine.ingest import execute_plan, IngestPlanError

    plan_data = yaml.safe_load(plan.read_text(encoding="utf-8"))
    config = _load_config_or_die()
    today = datetime.now().date()

    if dry_run:
        # Just validate the plan; report what would happen.
        from cp_engine.ingest import _validate_plan, _normalize_verb
        try:
            _validate_plan(plan_data)
        except IngestPlanError as exc:
            click.echo(f"Plan validation failed: {exc}", err=True)
            sys.exit(1)
        projects = plan_data.get("projects") or {}
        themes = plan_data.get("themes") or []
        account_decisions = plan_data.get("account_decisions") or []
        summary = {
            "valid": True,
            "projects_touched": list(projects.keys()),
            "verb_counts": {
                code: {_normalize_verb(v): len(items) for v, items in entries.items()}
                for code, entries in projects.items()
            },
            "themes_count": len(themes),
            "account_decisions_count": len(account_decisions),
        }
        click.echo(json.dumps(summary, indent=2))
        return

    try:
        result = execute_plan(plan_data, tenant_root=config.root, today=today)
    except IngestPlanError as exc:
        click.echo(f"Plan validation failed: {exc}", err=True)
        sys.exit(1)

    click.echo(json.dumps(result.to_dict(), indent=2))
    if result.errors:
        sys.exit(2)


@main.command("ingest-from-transcript")
@click.option(
    "--project",
    "project_code",
    required=True,
    help="Canonical project code (e.g. ggl-5168). One project per call.",
)
@click.option(
    "--transcript",
    "transcript_path",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    required=True,
    help="Path to the transcript file.",
)
@click.option(
    "--apply",
    is_flag=True,
    help="Execute the generated plan against the tenant. Default is to print YAML only.",
)
@click.option(
    "--model",
    default="claude-opus-4-7",
    show_default=True,
    help="Anthropic model to use for plan generation.",
)
@click.option(
    "--show-prompt",
    is_flag=True,
    help="Print the assembled prompt and exit without calling the API. For prompt-iteration debugging.",
)
def ingest_from_transcript_cmd(
    project_code: str,
    transcript_path: Path,
    apply: bool,
    model: str,
    show_prompt: bool,
) -> None:
    """Generate a cp ingest plan from a transcript via Claude (Phase C.1).

    By default prints the generated YAML to stdout for human review.
    With --apply, validates and executes the plan immediately.
    Requires ANTHROPIC_API_KEY in environment.
    """
    import json
    import yaml as _yaml

    from cp_engine.ingest import IngestPlanError, execute_plan
    from cp_engine.plan_from_transcript import (
        PlanGenerationError,
        _build_prompt,
        _load_project_context,
        _read_transcript,
        generate_plan,
    )

    config = _load_config_or_die()

    if show_prompt:
        prompt = _build_prompt(
            transcript=_read_transcript(transcript_path),
            project_context=_load_project_context(config, project_code),
            project_code=project_code,
            transcript_path=transcript_path,
            team=config.team,
        )
        click.echo(prompt)
        return

    try:
        result = generate_plan(
            config=config,
            project_code=project_code,
            transcript_path=transcript_path,
            model=model,
        )
    except PlanGenerationError as exc:
        click.echo(f"Plan generation failed: {exc}", err=True)
        sys.exit(1)

    yaml_output = _yaml.safe_dump(result.plan, sort_keys=False, allow_unicode=True)

    if not apply:
        click.echo(yaml_output)
        return

    try:
        exec_result = execute_plan(
            result.plan, tenant_root=config.root, today=datetime.now().date()
        )
    except IngestPlanError as exc:
        click.echo(f"Plan execution failed: {exc}", err=True)
        sys.exit(1)

    click.echo(json.dumps(exec_result.to_dict(), indent=2))
    if exec_result.errors:
        sys.exit(2)


@main.command("write-region")
@click.argument("file", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.argument("region")
@click.option("--body", help="New body content for the region.")
@click.option(
    "--body-file",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    help="Read body from a file instead.",
)
def write_region_cmd(
    file: Path, region: str, body: str | None, body_file: Path | None
) -> None:
    """Splice content into an engine-managed region (escape hatch).

    Usage:
      cp write-region 1p/ggl-5168-activation/cp.md inbound-strip --body-file new.md

    Logs a warning so this is visible when used. Routine writes should
    go through `cp ingest` or its structured verbs, not through this.
    """
    import logging
    from cp_engine.render import splice_managed_region

    if body is None and body_file is None:
        click.echo("Provide --body or --body-file.", err=True)
        sys.exit(1)
    new_body = body if body is not None else body_file.read_text(encoding="utf-8")

    logger = logging.getLogger("cp_engine.cli")
    logger.warning(
        "write-region called directly on %s region %r — routine writes "
        "should go through `cp ingest`. Using this is fine but visible.",
        file, region,
    )

    existing = file.read_text(encoding="utf-8")
    updated = splice_managed_region(existing, region, new_body)
    if updated != existing:
        file.write_text(updated)
        click.echo(f"wrote {file}")
    else:
        click.echo("no change")


@main.command("fathom-list")
@click.option(
    "--since",
    "since_iso",
    default=None,
    help="ISO timestamp; only return meetings newer than this. Default: most recent.",
)
@click.option("--limit", type=int, default=50, help="Max rows to return. Default 50.")
@click.option(
    "--type",
    "meeting_type",
    type=click.Choice([
        "project-status", "account-status", "sprint-planning",
        "work-session", "1-1", "untagged",
    ]),
    default=None,
    help="Filter by meeting_type (Phase B). Used by /cp-ingest --account to "
    "pull just account-status meetings. Default: no filter.",
)
def fathom_list_cmd(since_iso: str | None, limit: int, meeting_type: str | None) -> None:
    """List Fathom meetings from Supabase, newest first.

    Reads from `fathom_meetings` (the same Supabase project MC-2 uses;
    populated by the fathom-meeting-sync webhook). Lightweight rows —
    use `cp fathom-fetch <id>` to pull a full transcript.
    """
    import json
    from cp_engine.fathom import list_meetings

    config = _load_config_or_die()
    meetings = list_meetings(
        config, since_iso=since_iso, limit=limit, meeting_type=meeting_type
    )
    click.echo(json.dumps([m.to_dict() for m in meetings], indent=2))


@main.command("fathom-fetch")
@click.argument("meeting_id")
@click.option(
    "--needs-review",
    is_flag=True,
    help="Stage to transcripts/needs-review/ instead of transcripts/incoming/. "
    "Used by auto-poll when the confidence gate trips.",
)
def fathom_fetch_cmd(meeting_id: str, needs_review: bool) -> None:
    """Fetch a Fathom meeting from Supabase and stage its transcript to disk.

    Default location: `transcripts/incoming/<meeting-id>.txt` at the
    tenant root. Pass `--needs-review` to stage to needs-review/ instead.

    Output is JSON: `{path, meeting_id, title, project_tags, ...}`.
    Hand the path to /cp-ingest to deepen.
    """
    import json
    from cp_engine.fathom import fetch_meeting, stage_transcript

    config = _load_config_or_die()
    meeting = fetch_meeting(config, meeting_id)
    path = stage_transcript(meeting, tenant_root=config.root, needs_review=needs_review)
    click.echo(
        json.dumps(
            {
                "path": str(path),
                "meeting_id": meeting.id,
                "title": meeting.title,
                "meeting_date": meeting.meeting_date,
                "project_tags": meeting.project_tags,
                "meeting_type": meeting.meeting_type,
                "duration_minutes": meeting.duration_minutes,
                "needs_review": needs_review,
            },
            indent=2,
        )
    )


@main.command("fathom-auto-poll")
@click.option(
    "--limit",
    type=int,
    default=20,
    help="Max meetings to consider per poll. Default 20.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="List what would be staged + classified, but don't write files.",
)
def fathom_auto_poll_cmd(limit: int, dry_run: bool) -> None:
    """Poll Fathom Supabase for new meetings and stage them.

    Confidence gate: meetings with non-empty + non-`untagged` `project_tags`
    are staged to `transcripts/incoming/` for /cp-ingest. Meetings with no
    real tags go to `transcripts/needs-review/` for manual handling.

    State (last_polled_at + processed_ids) at `.cp-engine/state.json`
    (gitignored). Idempotent — already-processed ids are skipped.

    Output: JSON summary `{polled, staged_for_ingest[], staged_for_review[],
    skipped_already_processed[], errors[]}`.

    The `[fathom-ingest]` GitHub Actions workflow runs this on a cron and
    commits the staged files (not the deepening — /cp-ingest still requires
    /cp-ingest plugin orchestration which has Claude as the planner).
    """
    import json
    from cp_engine.fathom import (
        list_meetings,
        fetch_meeting,
        stage_transcript,
        has_good_tags,
        load_state,
        save_state,
        already_processed,
        mark_processed,
    )

    config = _load_config_or_die()
    state = load_state(config.root)
    meetings = list_meetings(config, since_iso=state.last_polled_at, limit=limit)

    summary: dict = {
        "polled": len(meetings),
        "staged_for_ingest": [],
        "staged_for_review": [],
        "skipped_already_processed": [],
        "errors": [],
    }

    for m in meetings:
        if already_processed(state, m.id):
            summary["skipped_already_processed"].append(m.id)
            continue
        try:
            target = "ingest" if has_good_tags(m.project_tags) else "review"
            if dry_run:
                bucket = "staged_for_ingest" if target == "ingest" else "staged_for_review"
                summary[bucket].append({"id": m.id, "title": m.title, "tags": m.project_tags})
                continue
            full = fetch_meeting(config, m.id)
            path = stage_transcript(
                full,
                tenant_root=config.root,
                needs_review=(target == "review"),
            )
            bucket = "staged_for_ingest" if target == "ingest" else "staged_for_review"
            summary[bucket].append(
                {"id": m.id, "title": m.title, "path": str(path), "tags": m.project_tags}
            )
            state = mark_processed(state, m.id)
        except Exception as exc:
            summary["errors"].append({"id": m.id, "error": str(exc)})

    if not dry_run:
        save_state(state, config.root)

    click.echo(json.dumps(summary, indent=2))


# ──────────────────────────────────────────────────────────────────────
#  Slack weekly-digest commands
# ──────────────────────────────────────────────────────────────────────


@main.command("slack-channels")
@click.option(
    "--format",
    "output_format",
    type=click.Choice(["table", "json"]),
    default="table",
    help="Output format. Default 'table'.",
)
@click.option(
    "--active-only",
    is_flag=True,
    help="Filter to active rows (engagements: Deal|Open; initiatives: Active).",
)
def slack_channels_cmd(output_format: str, active_only: bool) -> None:
    """List active engagement projects + initiatives + their Slack channels.

    Debug command for the weekly Slack digest pipeline. Each row is one
    engagement (`projects` row, non-internal) or internal initiative
    (`initiatives` row) with: canonical code, channel ids, enable_slack
    flag, and status.

    Use this to spot rows that need a channel_id backfill in MC-2 before
    turning on the cron.
    """
    import json
    from cp_engine.slack import list_channel_map

    config = _load_config_or_die()
    rows = list_channel_map(config)

    # Active = engagement (Deal|Open) OR initiative (Active).
    if active_only:
        rows = [r for r in rows if r.status in ("Deal", "Open", "Active")]

    if output_format == "json":
        click.echo(
            json.dumps(
                [
                    {
                        "code": r.code,
                        "name": r.name,
                        "company_code": r.company_code,
                        "status": r.status,
                        "enable_slack": r.enable_slack,
                        "channel_ids": list(r.channel_ids),
                        "primary_channel_id": r.primary_channel_id,
                        "primary_channel_name": r.primary_channel_name,
                    }
                    for r in rows
                ],
                indent=2,
            )
        )
        return

    # Table output.
    if not rows:
        click.echo("(no projects)")
        return

    code_w = max(len(r.code) for r in rows)
    name_w = min(40, max(len(r.name) for r in rows))
    headers = (
        f"{'CODE':<{code_w}}  {'STATUS':<7}  {'SLACK':<5}  "
        f"{'#CH':<3}  {'CHANNELS':<40}  NAME"
    )
    click.echo(headers)
    click.echo("-" * len(headers))
    n_mapped = 0
    n_unmapped = 0
    for r in rows:
        flag = "ON" if r.enable_slack else "OFF"
        n_ch = len(r.channel_ids)
        chans = ", ".join(r.channel_ids) if r.channel_ids else "(none)"
        chans_clip = chans if len(chans) <= 40 else chans[:39] + "…"
        name_clip = r.name if len(r.name) <= name_w else r.name[: name_w - 1] + "…"
        click.echo(
            f"{r.code:<{code_w}}  {r.status:<7}  {flag:<5}  "
            f"{n_ch:<3}  {chans_clip:<40}  {name_clip}"
        )
        if r.channel_ids:
            n_mapped += 1
        elif r.enable_slack:
            n_unmapped += 1
    click.echo()
    click.echo(f"{n_mapped} mapped, {n_unmapped} enable_slack=true with no channels")


def _parse_iso_week(week: str) -> tuple[datetime, datetime]:
    """Parse `YYYY-W##` → (monday_00:00_UTC, next_monday_00:00_UTC)."""
    import re as _re
    from datetime import timedelta

    m = _re.fullmatch(r"(\d{4})-W(\d{1,2})", week)
    if not m:
        raise click.BadParameter(
            f"week must be 'YYYY-W##' (e.g. '2026-W19'), got {week!r}"
        )
    year = int(m.group(1))
    wk = int(m.group(2))
    # ISO week date: Monday is weekday 1.
    monday = datetime.fromisocalendar(year, wk, 1).replace(tzinfo=timezone.utc)
    return monday, monday + timedelta(days=7)


@main.command("slack-fetch")
@click.option(
    "--code",
    "project_code",
    required=True,
    help="Canonical project code (e.g. ggl-5168). One project per call.",
)
@click.option(
    "--week",
    required=True,
    help="ISO week, e.g. '2026-W19'. Pulls Monday 00:00 UTC through "
    "next Monday 00:00 UTC.",
)
@click.option(
    "--format",
    "output_format",
    type=click.Choice(["text", "json"]),
    default="text",
    help="Output format. 'text' is human-readable; 'json' is for piping.",
)
def slack_fetch_cmd(project_code: str, week: str, output_format: str) -> None:
    """Pull one week of Slack messages for a single project.

    Resolves the project's `slack_channel_ids` from MC-2, then calls
    Slack's `conversations.history` for each channel and the ISO week.
    Filters bots, joins, reactions-only events; resolves user mentions.

    For multi-channel projects, prints one section per channel
    (separated by `# Channel: <id> (<name>)` headers).
    """
    import json
    from cp_engine.slack import (
        ChannelMapRow,
        SlackError,
        fetch_channels,
        list_channel_map,
        load_slack_token,
    )

    config = _load_config_or_die()
    monday, next_monday = _parse_iso_week(week)

    rows = list_channel_map(config)
    by_code: dict[str, ChannelMapRow] = {r.code: r for r in rows}
    row = by_code.get(project_code)
    if row is None:
        click.echo(f"Project {project_code!r} not found in MC-2.", err=True)
        sys.exit(2)
    if not row.channel_ids:
        click.echo(
            f"Project {project_code} has no Slack channels in MC-2 "
            "(use `cp slack-channels` to see the full map).",
            err=True,
        )
        sys.exit(2)

    try:
        token = load_slack_token(config)
        fetched = fetch_channels(
            token, row.channel_ids, monday, week_end=next_monday
        )
    except SlackError as exc:
        click.echo(f"Slack fetch failed: {exc}", err=True)
        sys.exit(1)

    if output_format == "json":
        click.echo(
            json.dumps(
                [
                    {
                        "channel_id": fc.channel_id,
                        "channel_name": fc.channel_name,
                        "messages": [
                            {"ts": m.ts, "iso": m.iso, "user_name": m.user_name, "text": m.text}
                            for m in fc.messages
                        ],
                    }
                    for fc in fetched
                ],
                indent=2,
            )
        )
        return

    total = sum(len(fc.messages) for fc in fetched)
    click.echo(
        f"# {project_code} · {week} · {len(fetched)} channel(s) · {total} message(s)\n"
    )
    for fc in fetched:
        name = f"#{fc.channel_name}" if fc.channel_name else "(unknown name)"
        click.echo(f"## Channel: {fc.channel_id} {name} · {len(fc.messages)} messages")
        for m in fc.messages:
            click.echo(f"[{m.iso} · {m.user_name}] {m.text}")
        click.echo()


@main.command("slack-digest")
@click.option(
    "--code",
    "project_code",
    default=None,
    help="Single project code (e.g. ggl-5168). Omit to iterate ALL active "
    "projects with `enable_slack=true` and a slack_channel_id.",
)
@click.option(
    "--week",
    required=True,
    help="ISO week, e.g. '2026-W19'. Pulls Monday 00:00 UTC through "
    "next Monday 00:00 UTC.",
)
@click.option(
    "--apply",
    is_flag=True,
    help="Execute the generated plan(s) against the tenant. Default is "
    "to print YAML to stdout only.",
)
@click.option(
    "--model",
    default="claude-opus-4-7",
    show_default=True,
    help="Anthropic model to use for plan generation.",
)
@click.option(
    "--skip-quiet/--include-quiet",
    default=True,
    help="When iterating multiple projects, skip channels with zero messages. "
    "Default: skip (quiet weeks don't get a 'no activity' bullet).",
)
def slack_digest_cmd(
    project_code: str | None,
    week: str,
    apply: bool,
    model: str,
    skip_quiet: bool,
) -> None:
    """Generate Slack-digest plan(s) for one week. Single project or all.

    Single-project mode (--code <code>): pulls the week's messages,
    generates one YAML plan, optionally applies it.

    Multi-project mode (no --code): iterates every active project with
    enable_slack=true and a slack_channel_id. Skips channels with zero
    messages by default. Produces one combined commit if --apply is set
    (P.4 phase — for now, applies each plan independently and prints a
    summary).
    """
    import json
    import yaml as _yaml
    from cp_engine.ingest import IngestPlanError, execute_plan
    from cp_engine.plan_from_slack import (
        SlackPlanError,
        generate_slack_plan,
    )
    from cp_engine.slack import (
        ChannelMapRow,
        SlackError,
        fetch_channels,
        list_channel_map,
        load_slack_token,
    )

    config = _load_config_or_die()
    monday, next_monday = _parse_iso_week(week)

    rows = list_channel_map(config)
    by_code: dict[str, ChannelMapRow] = {r.code: r for r in rows}

    if project_code:
        if project_code not in by_code:
            click.echo(f"Project {project_code!r} not found in MC-2.", err=True)
            sys.exit(2)
        targets = [by_code[project_code]]
    else:
        # Active = engagement (Deal|Open) OR initiative (Active),
        # plus enable_slack=true and ≥1 channel.
        targets = [
            r for r in rows
            if r.status in ("Deal", "Open", "Active")
            and r.enable_slack
            and r.channel_ids
        ]
        if not targets:
            click.echo("No active projects with Slack channels set.", err=True)
            sys.exit(1)

    try:
        token = load_slack_token(config)
    except SlackError as exc:
        click.echo(f"Slack auth failed: {exc}", err=True)
        sys.exit(1)

    summary = {
        "week": week,
        "projects": [],
    }

    for row in targets:
        if not row.channel_ids:
            click.echo(
                f"# skip {row.code}: no Slack channels", err=True
            )
            summary["projects"].append({"code": row.code, "skipped": "no_channels"})
            continue

        try:
            fetched = fetch_channels(
                token, row.channel_ids, monday, week_end=next_monday
            )
        except SlackError as exc:
            click.echo(f"# {row.code}: fetch failed: {exc}", err=True)
            summary["projects"].append({"code": row.code, "skipped": f"fetch_error: {exc}"})
            continue

        total_msgs = sum(len(fc.messages) for fc in fetched)
        if total_msgs == 0 and skip_quiet:
            click.echo(
                f"# skip {row.code}: 0 messages across {len(fetched)} channel(s) (quiet week)",
                err=True,
            )
            summary["projects"].append({"code": row.code, "skipped": "quiet_week"})
            continue

        click.echo(
            f"# {row.code} · {total_msgs} messages across {len(fetched)} channel(s) — generating plan…",
            err=True,
        )
        try:
            result = generate_slack_plan(
                config=config,
                project_code=row.code,
                week=week,
                channels=fetched,
                model=model,
            )
        except SlackPlanError as exc:
            click.echo(f"# {row.code}: plan generation failed: {exc}", err=True)
            summary["projects"].append({"code": row.code, "skipped": f"plan_error: {exc}"})
            continue

        if not apply:
            yaml_output = _yaml.safe_dump(
                result.plan, sort_keys=False, allow_unicode=True
            )
            click.echo(f"# --- {row.code} ---")
            click.echo(yaml_output)
            summary["projects"].append(
                {
                    "code": row.code,
                    "messages": total_msgs,
                    "channels": len(fetched),
                }
            )
            continue

        try:
            exec_result = execute_plan(
                result.plan,
                tenant_root=config.root,
                today=datetime.now().date(),
                week_iso=week,
            )
        except IngestPlanError as exc:
            click.echo(f"# {row.code}: plan execution failed: {exc}", err=True)
            summary["projects"].append({"code": row.code, "skipped": f"exec_error: {exc}"})
            continue

        summary["projects"].append(
            {
                "code": row.code,
                "messages": total_msgs,
                "channels": len(fetched),
                "files_written": [str(p) for p in exec_result.files_written],
                "skipped_duplicate": exec_result.skipped_duplicate,
                "errors": exec_result.errors,
            }
        )

    if apply:
        click.echo(json.dumps(summary, indent=2))


@main.command("prep-agenda")
@click.option(
    "--projects",
    "project_filter",
    default="",
    help="Comma-separated project codes to scope the agenda to. "
    "Empty (default) → full sprint planning across all active projects.",
)
@click.option(
    "--out",
    type=click.Path(dir_okay=False, path_type=Path),
    default=None,
    help="Write the agenda to this file path. Defaults to stdout.",
)
@click.option(
    "--summary",
    is_flag=True,
    help="Emit JSON metrics (workload by owner, coverage, urgency counts) "
    "instead of the rendered markdown. The /cp-prep plugin uses this.",
)
@click.option(
    "--no-sync",
    is_flag=True,
    help="Skip the automatic sync-if-stale check at the start. "
    "By default, prep-agenda auto-runs `cp sync` if master-cp's last sync "
    "is more than 10 minutes old, so the agenda never shows stale data.",
)
def prep_agenda_cmd(
    project_filter: str, out: Path | None, summary: bool, no_sync: bool
) -> None:
    """Render a sprint-planning agenda from current cp tenant state.

    Reads master-cp's project list, weekly-cp.md decisions, current-week
    sprint files, and per-project cp.md Quick Resume sections; cross-
    references everything into project-grouped blocks.

    Default: agenda for all active projects (full sprint planning).
    With `--projects <code>,<code>...`: scoped agenda for those projects only.

    Output is markdown. Default to stdout; pass `--out sprints/<W##>/_agenda.md`
    to overwrite the per-week agenda file. Pass `--summary` to emit JSON
    metrics instead (used by the /cp-prep plugin command).

    Deprecated as of v0.15.0 — superseded by ``cp prep-planning``, which
    produces a forward-looking, account-grouped sprint-planning doc with
    ClickUp-sourced milestones. ``cp prep-agenda`` will be removed in a
    future release.
    """
    import json
    from datetime import datetime, timedelta
    from cp_engine.agenda import build_agenda, build_agenda_summary, is_sync_stale
    from cp_engine.sync import _default_backend_factory, sync_tenant

    click.echo(
        "warning: 'cp prep-agenda' is deprecated and will be removed in a future "
        "release. Use 'cp prep-planning' instead.",
        err=True,
    )

    config = _load_config_or_die()

    # v0.8.8.2: auto-sync if stale. Avoids the "agenda shows yesterday's
    # owner data" footgun. Opt-out via --no-sync for environments where
    # the network round-trip isn't acceptable (CI dry-runs, etc.).
    if not no_sync and is_sync_stale(config):
        click.echo("master-cp sync is stale; running cp sync first…", err=True)
        try:
            sync_tenant(config)
        except Exception as exc:
            click.echo(f"sync failed (continuing with stale data): {exc}", err=True)

    backend = _default_backend_factory(config.sync.backend)
    projects = backend.read_projects(config)

    # Pull last-week allocations the same way master-cp does, so the agenda's
    # per-project "last sprint hours" line matches what's in master-cp.md.
    today = datetime.now().date()
    last_monday = today - timedelta(days=today.weekday() + 7)
    try:
        allocations = backend.read_allocations(config, last_monday.isoformat())
    except Exception:
        allocations = None

    last_sprint_hours_by_project: dict[str, str] = {}
    if allocations and getattr(allocations, "by_project", None):
        for code, alloc in allocations.by_project.items():
            entries = [f"{e.person_name.split()[0]} {e.hours:g}h" for e in alloc.entries]
            if entries:
                last_sprint_hours_by_project[code] = ", ".join(entries)

    code_filter = tuple(c.strip() for c in project_filter.split(",") if c.strip()) or None

    if summary:
        s = build_agenda_summary(
            config,
            tuple(projects),
            today=today,
            project_filter=code_filter,
            last_sprint_hours_by_project=last_sprint_hours_by_project,
        )
        click.echo(json.dumps(s.to_dict(), indent=2))
        return

    agenda_md = build_agenda(
        config,
        tuple(projects),
        today=today,
        project_filter=code_filter,
        last_sprint_hours_by_project=last_sprint_hours_by_project,
    )

    if out:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(agenda_md)
        click.echo(f"wrote {out}")
    else:
        click.echo(agenda_md)


@main.command("prep-planning")
@click.option(
    "--projects",
    "project_filter",
    default="",
    help="Comma-separated project codes to scope the doc to. "
    "Empty (default) → all active projects across the tenant.",
)
@click.option(
    "--out",
    type=click.Path(dir_okay=False, path_type=Path),
    default=None,
    help="Write the planning doc to this file path. Defaults to stdout.",
)
@click.option(
    "--summary",
    is_flag=True,
    help="Emit a JSON summary (milestone counts, urgent counts, errors) "
    "instead of the rendered markdown. The /cp-prep-planning plugin uses this.",
)
def prep_planning_cmd(
    project_filter: str, out: Path | None, summary: bool
) -> None:
    """Render a forward-looking sprint-planning doc.

    Pulls per-project milestones from ClickUp (matched to each project's
    ``clickup_list_id`` in MC-2) and assembles an account-grouped doc with
    Where / Forward calendar / Open commitments per project. Replaces
    ``cp prep-agenda`` for sprint planning.

    Default: full doc across all active engagements + initiatives.
    With ``--projects <code>,<code>``: scoped to those projects only.

    Default writes markdown to stdout. ``--out sprints/<W##>/_planning.md``
    persists it; ``--summary`` emits JSON instead.
    """
    from datetime import datetime, timedelta

    from cp_engine.prep_planning import (
        render_planning_doc,
        render_planning_summary,
    )
    from cp_engine.sync import _default_backend_factory

    config = _load_config_or_die()

    backend = _default_backend_factory(config.sync.backend)
    projects = backend.read_projects(config)

    # Pull last-week allocations the same way prep-agenda does so the tenant
    # strip stays consistent with the rest of cp's surfacing.
    today = datetime.now().date()
    last_monday = today - timedelta(days=today.weekday() + 7)
    tenant_hours: dict[str, int] = {}
    try:
        allocations = backend.read_allocations(config, last_monday.isoformat())
    except Exception:
        allocations = None
    if allocations is not None:
        rollup = getattr(allocations, "rollup", ()) or ()
        for entry in rollup:
            name = entry.person_name.split()[0] if entry.person_name else None
            if name:
                tenant_hours[name] = int(round(entry.total_hours))

    # MC-2 Supabase client for clickup_list_id resolution. Silent degrade if
    # creds aren't set — per-project blocks will render "(ClickUp list not set)".
    from cp_engine.prep_planning import _make_supabase_client, _resolve_clickup_token
    supabase_client = _make_supabase_client(config)

    # ClickUp token: env first, then <mc-2 clone>/backend/.env (accepting both
    # CLICKUP_API_TOKEN and CLICKUP_API_KEY). Resolved here where config is
    # available — without it, a fresh shell resolves nothing and every
    # project's Forward Calendar renders empty.
    clickup_token = _resolve_clickup_token(config)

    code_filter = tuple(c.strip() for c in project_filter.split(",") if c.strip()) or None

    # Pre-fetch the cp_ask_hash → clickup_task_id map for bridging-period
    # dedupe (Open Commitments would otherwise render an ask once as a
    # ClickUp client-ask and once as a sprint-file fallback). Scan each
    # active project's current sprint file for hashes; degrade silently on
    # any failure since the dedupe is a polish, not load-bearing.
    clickup_task_ids: dict[str, str] = {}
    try:
        from cp_engine.prep_planning import (
            _parse_sprint_open_asks,
            filter_active,
        )
        from cp_engine.sprints import current_sprint_week_iso

        week_iso_for_dedupe = current_sprint_week_iso(
            datetime.combine(today, datetime.min.time())
        )
        wanted_codes = (
            {c.lower() for c in code_filter} if code_filter else None
        )
        all_hashes: list[str] = []
        for p in filter_active(projects):
            if wanted_codes is not None and p.code.lower() not in wanted_codes:
                continue
            sprint_path = (
                config.root / "sprints" / week_iso_for_dedupe / f"{p.code}.md"
            )
            for a in _parse_sprint_open_asks(sprint_path):
                if a["hash"]:
                    all_hashes.append(a["hash"])
        if all_hashes:
            clickup_task_ids = _fetch_clickup_task_ids_for_hashes(
                config, all_hashes
            )
    except Exception:  # noqa: BLE001 — dedupe must not break the doc
        clickup_task_ids = {}

    if summary:
        out_str = render_planning_summary(
            config,
            tuple(projects),
            today=today,
            project_filter=code_filter,
            tenant_hours_last_week=tenant_hours,
            supabase_client=supabase_client,
            clickup_token=clickup_token,
            clickup_task_ids=clickup_task_ids,
        )
        click.echo(out_str)
        return

    doc = render_planning_doc(
        config,
        tuple(projects),
        today=today,
        project_filter=code_filter,
        tenant_hours_last_week=tenant_hours,
        supabase_client=supabase_client,
        clickup_token=clickup_token,
        clickup_task_ids=clickup_task_ids,
    )

    if out:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(doc)
        click.echo(f"wrote {out}")
    else:
        click.echo(doc)


@main.command("attention-digest")
@click.option(
    "--post-to-slack",
    is_flag=True,
    help="Post the digest as a Slack DM to configured recipients.",
)
@click.option(
    "--recipient",
    default="Drew",
    show_default=True,
    help="Recipient name used in the digest greeting.",
)
@click.option(
    "--today",
    type=click.DateTime(formats=["%Y-%m-%d"]),
    default=None,
    help="Override today's date (YYYY-MM-DD). Useful for testing.",
)
def attention_digest_cmd(post_to_slack: bool, recipient: str, today) -> None:
    """Print today's attention digest (past-due asks, escalated risks).

    Scans the current ISO-week sprint dir for past-due open asks and
    recently-escalated risks, then renders a Slack-flavored markdown
    digest. Default prints to stdout; `--post-to-slack` DMs the digest
    to each Slack user ID listed in `[attention_digest].recipients`.
    """
    from datetime import date as _date
    from cp_engine.attention_digest import (
        _post_digest_to_recipients,
        attention_digest as run_digest,
        compose_digest,
    )

    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    today_date = today.date() if today else _date.today()
    digest = run_digest(config=config, today=today_date)
    markdown = compose_digest(digest, recipient_name=recipient, today=today_date)

    if post_to_slack:
        from cp_engine.slack import SlackError
        # Look up ClickUp task IDs for past-due asks so the Block Kit
        # renderer can emit "Open in ClickUp" link buttons instead of
        # Resolve/Snooze for asks already pushed via v0.12's pipeline.
        # Degrades to {} on any failure — digest send must not fail.
        clickup_task_ids: dict[str, str] = {}
        if digest.get("past_due"):
            hashes = [a.hash for a in digest["past_due"]]
            clickup_task_ids = _fetch_clickup_task_ids_for_hashes(config, hashes)
        try:
            timestamps = _post_digest_to_recipients(
                config=config,
                digest=digest,
                recipient_name=recipient,
                clickup_task_ids=clickup_task_ids,
            )
        except SlackError as exc:
            click.echo(f"Slack post failed: {exc}", err=True)
            sys.exit(1)
        click.echo(
            f"Posted digest to {len(timestamps)} recipient(s).", err=False
        )
        return

    click.echo(markdown.rstrip("\n"))


def _fetch_clickup_task_ids_for_hashes(config, hashes: list[str]) -> dict[str, str]:
    """Map each cp_ask_hash to its clickup_task_id (if any).

    Returns {} on any failure — Supabase missing, query error, network. The
    digest must still send when this helper degrades, because the
    Slack-button UX is a nice-to-have on top of the existing markdown digest.
    """
    import logging
    import os

    log = logging.getLogger(__name__)

    if not hashes:
        return {}
    try:
        from supabase import create_client
        url = os.environ.get("SUPABASE_URL")
        key = os.environ.get("SUPABASE_SERVICE_KEY") or os.environ.get("SUPABASE_KEY")
        if not url or not key:
            log.info("clickup task-id lookup skipped: SUPABASE env not set")
            return {}
        client = create_client(url, key)
        resp = (
            client.table("clickup_task_proposals")
            .select("cp_ask_hash, clickup_task_id")
            .in_("cp_ask_hash", hashes)
            .not_.is_("clickup_task_id", "null")
            .execute()
        )
        return {
            row["cp_ask_hash"]: row["clickup_task_id"]
            for row in (resp.data or [])
            if row.get("clickup_task_id")
        }
    except Exception as exc:  # noqa: BLE001 — digest send must not fail
        log.warning("clickup task-id lookup failed (degrading to no links): %s", exc)
        return {}


def _load_config_or_die() -> "TenantConfig":  # noqa: F821
    """Load tenant config from cwd; exit with a friendly error on failure."""
    try:
        return load(Path.cwd())
    except CommittedConfigMissing:
        click.echo(
            "No .cp-engine.toml in this directory. Run `cp init` "
            "or cd into the cp tenant root.",
            err=True,
        )
        sys.exit(1)
    except ConfigError as exc:
        click.echo(f"Config error: {exc}", err=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
