"""The `cp` CLI — entry point for tenant operations.

Subcommands per spec v02 §2.1:
  cp init     → walk through populating .cp-engine.local.toml
  cp sync     → run one sync cycle locally (same logic as the Action)
  cp render   → re-render generated files (master-cp.md, CLAUDE.md)
  cp status   → show what would change without writing
"""

from __future__ import annotations

import sys
from pathlib import Path

import click

from cp_engine.config import ConfigError, load
from cp_engine.config import CommittedConfigMissing
from cp_engine.init import InitAborted, run_init
from cp_engine.sync import SyncError, sync_tenant


@click.group()
@click.version_option(package_name="cp-engine")
def main() -> None:
    """Context Protocol Engine — tenant operations."""


@main.command()
@click.option(
    "--non-interactive",
    is_flag=True,
    help="Don't prompt; mark every committed project as skipped (useful in CI).",
)
def init(non_interactive: bool) -> None:
    """Walk through populating .cp-engine.local.toml interactively."""
    try:
        run_init(Path.cwd(), interactive=not non_interactive)
    except CommittedConfigMissing as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)
    except InitAborted as exc:
        click.echo(str(exc), err=True)
        sys.exit(1)
    except KeyboardInterrupt:
        click.echo("\nAborted. Partial progress (if any) has been saved.", err=True)
        sys.exit(130)


@main.command()
def sync() -> None:
    """Run one sync cycle for the current tenant."""
    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    try:
        result = sync_tenant(config)
    except SyncError as exc:
        click.echo(f"Sync failed: {exc}", err=True)
        sys.exit(1)

    if result.no_op:
        click.echo(f"No changes ({result.projects_seen} projects checked).")
        return

    click.echo(f"Synced {result.projects_seen} projects.")
    for path in result.files_written:
        click.echo(f"  wrote    {path.relative_to(config.root)}")
    for path in result.files_archived:
        click.echo(f"  archived {path.relative_to(config.root)}")


@main.command()
def render() -> None:
    """Re-render generated files (alias for `cp sync` in v0.1)."""
    # In v0.1 there's no separate render-only path — sync already writes
    # only when content changed and never reaches out to the database
    # for unchanged regions. Future: a true `--no-network` render that
    # uses cached project state.
    click.echo("`cp render` is currently an alias for `cp sync`. Running sync…")
    ctx = click.get_current_context()
    ctx.invoke(sync)


@main.command(name="refresh-pristine")
@click.option(
    "--dry-run",
    is_flag=True,
    help="Show what would be refreshed without writing.",
)
def refresh_pristine(dry_run: bool) -> None:
    """Re-scaffold project CPs that have no hand-written content.

    A project CP is "pristine" if it still contains the placeholder text
    that the scaffold inserted ("<one-line description of what this
    project is and who it's for>"). Pristine CPs were generated by an
    older engine version and have outdated provenance, missing
    metadata blocks, or wrong section structures (e.g. v0.1 templates
    didn't have project-facts; v0.2 templates do).

    Edited CPs (the placeholder is gone or any other section was filled
    in) are NEVER touched — that's hand-written content the engine has
    no business overwriting.

    Use this once after upgrading cp-engine versions to refresh the
    template shape across the tenant.
    """
    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    from cp_engine.refresh import refresh_pristine_cps

    try:
        result = refresh_pristine_cps(config, dry_run=dry_run)
    except SyncError as exc:
        click.echo(f"Refresh failed: {exc}", err=True)
        sys.exit(1)

    if not result.pristine_files:
        click.echo("No pristine project CPs found. Nothing to refresh.")
        return

    if dry_run:
        click.echo(f"Would refresh {len(result.pristine_files)} pristine project CP(s):")
    else:
        click.echo(f"Refreshed {len(result.pristine_files)} pristine project CP(s):")
    for path in result.pristine_files:
        click.echo(f"  {path.relative_to(config.root)}")
    if result.skipped_files:
        click.echo(f"\nSkipped {len(result.skipped_files)} edited CP(s) (hand-written content preserved).")


@main.command(name="migrate-to-v03")
@click.option(
    "--dry-run",
    is_flag=True,
    help="Show what would move without touching the disk.",
)
def migrate_to_v03(dry_run: bool) -> None:
    """One-shot move of v0.2's flat `projects/<code>.md` layout to v0.3's
    per-project working dirs at `<scope>/projects/<code>/cp.md`.

    Uses `git mv` to preserve rename detection. Refuses to run on a dirty
    working tree — commit or stash first. After this runs cleanly, regular
    `cp sync` keeps using the new layout."""
    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    from cp_engine.migrate import MigrationError, migrate_to_v03 as _run

    try:
        result = _run(config, dry_run=dry_run)
    except MigrationError as exc:
        click.echo(f"Migration aborted: {exc}", err=True)
        sys.exit(1)
    except SyncError as exc:
        click.echo(f"Migration aborted: {exc}", err=True)
        sys.exit(1)

    label = "Would move" if dry_run else "Moved"
    if not result.moved and not result.skipped:
        click.echo("Nothing to migrate — no v0.2 layout files found.")
        return

    click.echo(f"{label} {len(result.moved)} file(s):")
    for src, dst in result.moved:
        click.echo(f"  {src.relative_to(config.root)} → {dst.relative_to(config.root)}")
    if result.skipped:
        click.echo(f"\nSkipped {len(result.skipped)} file(s) — resolve by hand:")
        for src, reason in result.skipped:
            click.echo(f"  {src.relative_to(config.root)}: {reason}")

    if not dry_run:
        click.echo(
            "\nReview the changes, then commit:\n"
            "  git status\n"
            '  git commit -m "cp-engine v0.3: restructure to per-project working directories"'
        )


@main.command()
def status() -> None:
    """Show what would change on next sync (no writes — read-only)."""
    click.echo("cp status — not implemented yet (lands in v0.4)")
    sys.exit(1)


if __name__ == "__main__":
    main()
