"""The `cp` CLI — entry point for tenant operations.

Subcommands per spec v02 §2.1:
  cp init     → walk through populating .cp-engine.local.toml
  cp sync     → run one sync cycle locally (same logic as the Action)
  cp render   → re-render generated files (master-cp.md, CLAUDE.md)
  cp status   → show what would change without writing
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

import click

from cp_engine.config import ConfigError, load
from cp_engine.config import CommittedConfigMissing
from cp_engine.init import InitAborted, run_init
from cp_engine.sync import SyncError, sync_tenant


@click.group()
@click.version_option(package_name="cp-engine")
def main() -> None:
    """Context Protocol Engine — tenant operations."""


@main.command()
@click.option(
    "--non-interactive",
    is_flag=True,
    help="Don't prompt; mark every committed project as skipped (useful in CI).",
)
def init(non_interactive: bool) -> None:
    """Walk through populating .cp-engine.local.toml interactively."""
    try:
        run_init(Path.cwd(), interactive=not non_interactive)
    except CommittedConfigMissing as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)
    except InitAborted as exc:
        click.echo(str(exc), err=True)
        sys.exit(1)
    except KeyboardInterrupt:
        click.echo("\nAborted. Partial progress (if any) has been saved.", err=True)
        sys.exit(130)


@main.command()
def sync() -> None:
    """Run one sync cycle for the current tenant."""
    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    try:
        result = sync_tenant(config)
    except SyncError as exc:
        click.echo(f"Sync failed: {exc}", err=True)
        sys.exit(1)

    if result.no_op:
        click.echo(f"No changes ({result.projects_seen} projects checked).")
        return

    click.echo(f"Synced {result.projects_seen} projects.")
    for path in result.files_written:
        click.echo(f"  wrote    {path.relative_to(config.root)}")
    for path in result.files_deactivated:
        click.echo(f"  deactivated {path.relative_to(config.root)}")


@main.command()
def render() -> None:
    """Re-render generated files (alias for `cp sync` in v0.1)."""
    # In v0.1 there's no separate render-only path — sync already writes
    # only when content changed and never reaches out to the database
    # for unchanged regions. Future: a true `--no-network` render that
    # uses cached project state.
    click.echo("`cp render` is currently an alias for `cp sync`. Running sync…")
    ctx = click.get_current_context()
    ctx.invoke(sync)


@main.command(name="refresh-pristine")
@click.option(
    "--dry-run",
    is_flag=True,
    help="Show what would be refreshed without writing.",
)
def refresh_pristine(dry_run: bool) -> None:
    """Re-scaffold project CPs that have no hand-written content.

    A project CP is "pristine" if it still contains the placeholder text
    that the scaffold inserted ("<one-line description of what this
    project is and who it's for>"). Pristine CPs were generated by an
    older engine version and have outdated provenance, missing
    metadata blocks, or wrong section structures (e.g. v0.1 templates
    didn't have project-facts; v0.2 templates do).

    Edited CPs (the placeholder is gone or any other section was filled
    in) are NEVER touched — that's hand-written content the engine has
    no business overwriting.

    Use this once after upgrading cp-engine versions to refresh the
    template shape across the tenant.
    """
    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    from cp_engine.refresh import refresh_pristine_cps

    try:
        result = refresh_pristine_cps(config, dry_run=dry_run)
    except SyncError as exc:
        click.echo(f"Refresh failed: {exc}", err=True)
        sys.exit(1)

    if not result.pristine_files:
        click.echo("No pristine project CPs found. Nothing to refresh.")
        return

    if dry_run:
        click.echo(f"Would refresh {len(result.pristine_files)} pristine project CP(s):")
    else:
        click.echo(f"Refreshed {len(result.pristine_files)} pristine project CP(s):")
    for path in result.pristine_files:
        click.echo(f"  {path.relative_to(config.root)}")
    if result.skipped_files:
        click.echo(f"\nSkipped {len(result.skipped_files)} edited CP(s) (hand-written content preserved).")


@main.command(name="migrate-to-v03")
@click.option(
    "--dry-run",
    is_flag=True,
    help="Show what would move without touching the disk.",
)
def migrate_to_v03(dry_run: bool) -> None:
    """One-shot move of v0.2's flat `projects/<code>.md` layout to v0.3's
    per-project working dirs at `<scope>/projects/<code>/cp.md`.

    Uses `git mv` to preserve rename detection. Refuses to run on a dirty
    working tree — commit or stash first. After this runs cleanly, regular
    `cp sync` keeps using the new layout."""
    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    from cp_engine.migrate import MigrationError, migrate_to_v03 as _run

    try:
        result = _run(config, dry_run=dry_run)
    except MigrationError as exc:
        click.echo(f"Migration aborted: {exc}", err=True)
        sys.exit(1)
    except SyncError as exc:
        click.echo(f"Migration aborted: {exc}", err=True)
        sys.exit(1)

    label = "Would move" if dry_run else "Moved"
    if not result.moved and not result.skipped:
        click.echo("Nothing to migrate — no v0.2 layout files found.")
        return

    click.echo(f"{label} {len(result.moved)} file(s):")
    for src, dst in result.moved:
        click.echo(f"  {src.relative_to(config.root)} → {dst.relative_to(config.root)}")
    if result.skipped:
        click.echo(f"\nSkipped {len(result.skipped)} file(s) — resolve by hand:")
        for src, reason in result.skipped:
            click.echo(f"  {src.relative_to(config.root)}: {reason}")

    if not dry_run:
        click.echo(
            "\nReview the changes, then commit:\n"
            "  git status\n"
            '  git commit -m "cp-engine v0.3: restructure to per-project working directories"'
        )


@main.command(name="capture-session")
@click.option(
    "--source-repo",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help="Source repo path (a code repo with a .cp-link). Mutually exclusive with --working-dir.",
)
@click.option(
    "--working-dir",
    "working_dir",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help=(
        "cp working-dir path (for content-only projects with no separate "
        "source repo). Mutually exclusive with --source-repo. The cp tenant "
        "root is found by walking up for .cp-engine.toml, so --cp-tenant "
        "isn't needed."
    ),
)
@click.option(
    "--summary-file",
    "summary_file",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    required=True,
    help="Path to a file containing the session summary (Claude writes this).",
)
@click.option(
    "--user",
    required=True,
    help="Display name for the session author (e.g. \"Drew\").",
)
@click.option(
    "--cp-tenant",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help="Path to the cp tenant clone. Required for unlinked source repos.",
)
@click.option("--no-commit", is_flag=True, help="Don't run git add/commit/push.")
@click.option("--no-push", is_flag=True, help="Commit but don't push.")
def capture_session_cmd(
    source_repo: Path | None,
    working_dir: Path | None,
    summary_file: Path,
    user: str,
    cp_tenant: Path | None,
    no_commit: bool,
    no_push: bool,
) -> None:
    """Write a session summary back to the cp tree.

    Two modes:

    \b
    --source-repo <path>  (default: cwd)
        For source-code repos with a .cp-link. Resolves destination via
        the link (self-healing if stale), or falls back to
        <cp-tenant>/exceptions/ for untracked repos.

    --working-dir <path>
        For content-only projects (1P engagements without a code repo).
        Skips source-repo resolution; writes directly to <path>/sessions/.
        The cp tenant root is found by walking up for .cp-engine.toml.

    Both modes write `<wd>/sessions/<YYYY-MM-DD>-<HHMM>-<user>.md`,
    update the project's `cp.md` Last session line, and commit + push.
    """
    from cp_engine.capture_session import (
        CaptureSessionError,
        capture_session,
        capture_session_in_working_dir,
    )

    if source_repo is not None and working_dir is not None:
        click.echo(
            "Error: pass --source-repo or --working-dir, not both.", err=True
        )
        sys.exit(2)

    summary_text = summary_file.read_text(encoding="utf-8")

    try:
        if working_dir is not None:
            result = capture_session_in_working_dir(
                working_dir=working_dir,
                summary_text=summary_text,
                user=user,
                commit=not no_commit,
                push=not (no_commit or no_push),
            )
        else:
            repo = (source_repo or Path.cwd()).resolve()
            result = capture_session(
                source_repo=repo,
                summary_text=summary_text,
                user=user,
                cp_tenant=cp_tenant,
                commit=not no_commit,
                push=not (no_commit or no_push),
            )
    except CaptureSessionError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(1)

    if result.is_exception:
        click.echo(
            f"Logged exception (repo not tracked in this cp tenant): "
            f"{result.summary_path}"
        )
    else:
        click.echo(f"Wrote session summary: {result.summary_path}")
        if result.cp_md_updated:
            click.echo("Updated cp.md Last session line.")
        if result.extra_files_committed:
            click.echo(
                f"Also committed {len(result.extra_files_committed)} other file(s) "
                f"in the working dir (binaries excluded by .gitignore):"
            )
            wd = result.cp_working_dir
            for p in result.extra_files_committed:
                rel = p.relative_to(wd) if wd else p
                click.echo(f"  {rel}")
    if result.commit_sha:
        # Distinguish actually-skipped (--no-push or --no-commit) from
        # actually-pushed from rebased-then-pushed. Push *failures* now
        # raise PushFailed and are surfaced via the CaptureSessionError
        # branch above, so reaching here with pushed=False means the
        # caller asked us not to push.
        if result.push_rebased:
            click.echo(
                f"Committed {result.commit_sha}, rebased on top of upstream, "
                "and pushed."
            )
        elif result.pushed:
            click.echo(f"Committed {result.commit_sha} and pushed.")
        else:
            click.echo(f"Committed {result.commit_sha} (push skipped).")


@main.command(name="project-context")
@click.option(
    "--working-dir",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help="cp working dir. Defaults to cwd.",
)
@click.option("--user", help="Which `[local-repos.<user>]` entry to use.")
@click.option("--days", type=int, default=7, help="Lookback window. Default 7.")
def project_context_cmd(
    working_dir: Path | None,
    user: str | None,
    days: int,
) -> None:
    """Print recent activity for a project: git log + session captures.

    Run from inside a cp working dir. Reads the linked source repo's
    local clone path from `<tenant>/.cp-engine.toml [local-repos.<user>]`,
    runs `git log --since=<days> ago` there, lists session files in the
    working dir's `sessions/` directory from the same window, and prints
    one chronological timeline.
    """
    from cp_engine.project_context import ProjectContextError, project_context

    wd = (working_dir or Path.cwd()).resolve()
    try:
        result = project_context(working_dir=wd, user=user, days=days)
    except ProjectContextError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(1)

    click.echo(f"# {result.repo_name} — last {result.window_days} days")
    if result.github_url:
        click.echo(f"GitHub: {result.github_url}")
    click.echo(f"Local clone: {result.local_clone or '(not on this machine)'}")
    click.echo()

    if not result.commits and not result.sessions:
        click.echo("(no activity in window)")
        return

    # Merge commits + sessions on one timeline. Each entry has a `.when`
    # attribute; sort newest first.
    timeline: list[tuple[datetime, str]] = []
    for c in result.commits:
        line = (
            f"  {c.when.strftime('%Y-%m-%d %H:%M')}  commit {c.sha}  "
            f"({c.author}) {c.subject}"
        )
        timeline.append((c.when, line))
    for s in result.sessions:
        one = s.one_liner or "(no summary)"
        line = (
            f"  {s.when.strftime('%Y-%m-%d %H:%M')}  session         "
            f"({s.user}) {one}"
        )
        timeline.append((s.when, line))
    timeline.sort(key=lambda t: t[0], reverse=True)
    for _when, line in timeline:
        click.echo(line)
    click.echo()
    click.echo(f"({len(result.commits)} commits, {len(result.sessions)} sessions)")


@main.command(name="link-local")
def link_local_cmd() -> None:
    """Wire `.cp-link` files into each source repo named in `[local-repos]`.

    Reads `.cp-engine.local.toml`'s `[local-repos]` table, validates each
    path is a git repo whose remote matches the entry, finds the
    corresponding cp working dir by walking the cp tenant tree, and writes
    `<source-repo>/.cp-link` containing the absolute path of that working
    dir. Also adds `.cp-link` to `.git/info/exclude` so the source repo
    won't accidentally commit it.

    Idempotent — re-running with no changes is a no-op.
    """
    try:
        config = load(Path.cwd())
    except ConfigError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    from cp_engine.link_local import LinkLocalError, link_local as _run

    if not config.local_repos:
        click.echo(
            "No [local-repos] entries in .cp-engine.local.toml. Add one per "
            "repo you want linked, e.g.:\n\n"
            "  [local-repos]\n"
            '  "mc-2"      = "/Users/you/Documents/Python/mc-2"\n'
            '  "cp-engine" = "/Users/you/Documents/Python/context-protocol"\n'
        )
        return

    try:
        results = _run(config)
    except LinkLocalError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(1)

    wrote = sum(1 for r in results if r.wrote_link)
    excluded = sum(1 for r in results if r.excluded)
    for r in results:
        action = "wrote" if r.wrote_link else "ok   "
        click.echo(f"  {action} {r.source_repo_path}/.cp-link → {r.cp_working_dir}")
    click.echo(
        f"\n{len(results)} repo(s) linked. "
        f"{wrote} new/updated link file(s); "
        f"{excluded} .git/info/exclude update(s)."
    )


@main.command()
def status() -> None:
    """Show what would change on next sync (no writes — read-only)."""
    click.echo("cp status — not implemented yet (lands in v0.4)")
    sys.exit(1)


@main.command(name="migrate-projects-flat")
@click.option(
    "--tenant-root",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=None,
    help="Tenant root (default: current directory).",
)
def migrate_projects_flat_cmd(tenant_root: Path | None) -> None:
    """One-shot move of pre-v0.7's `<scope>/projects/<dir>` layout to v0.7's
    `<scope>/<dir>` layout.

    Uses `git mv` to preserve rename detection. Refuses to run on a dirty
    working tree — commit or stash first. Idempotent: re-running on an
    already-migrated tree is a no-op. After this runs cleanly, regular
    `cp sync` keeps using the new layout.

    Also rewrites `.cp-link` files in linked source repos so they point
    at the new working-dir paths."""
    from cp_engine.migrate_flat import MigrateFlatError, migrate_projects_flat

    root = tenant_root or Path.cwd()
    try:
        result = migrate_projects_flat(root)
    except MigrateFlatError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    if result.no_op:
        click.echo("Nothing to migrate (tree already matches v0.7 layout).")
        return

    for src, dst in result.moved_dirs:
        click.echo(f"  moved: {src.relative_to(root)} → {dst.relative_to(root)}")
    for path in result.removed_projects_dirs:
        click.echo(f"  removed empty: {path.relative_to(root)}")
    for path in result.rewrote_cp_links:
        click.echo(f"  rewrote .cp-link: {path}")
    click.echo(
        f"\nDone. Review the staged changes (`git status`) and commit when "
        f"satisfied. Source-repo .cp-link files are not under git control "
        f"so they were updated in place."
    )


@main.command(name="resolve-engine-pin")
@click.option(
    "--tenant-root",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=None,
    help="Tenant root (default: current directory).",
)
@click.option(
    "--format",
    "output_format",
    type=click.Choice(["tag", "pip-spec", "json"]),
    default="tag",
    help="Output format. tag=v0.6.0; pip-spec=full git+url@tag; json=structured.",
)
def resolve_engine_pin_cmd(tenant_root: Path | None, output_format: str) -> None:
    """Resolve [engine].version constraint to the highest matching git tag.

    Used by the GitHub Actions runner so bumping the tenant pin is
    sufficient to pick up a new engine release — no workflow edit needed.
    """
    from cp_engine.pin_resolver import ENGINE_REPO_URL, PinResolutionError, resolve_for_tenant

    root = tenant_root or Path.cwd()
    try:
        resolution = resolve_for_tenant(root)
    except PinResolutionError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(2)

    if output_format == "tag":
        click.echo(resolution.tag)
    elif output_format == "pip-spec":
        click.echo(f"cp-engine @ git+{ENGINE_REPO_URL}@{resolution.tag}")
    else:
        import json

        click.echo(
            json.dumps(
                {
                    "constraint": resolution.constraint,
                    "tag": resolution.tag,
                    "version": str(resolution.version),
                }
            )
        )


@main.command("parse-sprint")
@click.argument("path", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option("--json", "as_json", is_flag=True, help="Emit JSON to stdout.")
def parse_sprint_cmd(path: Path, as_json: bool) -> None:
    """Parse a sprint file and emit its structured representation.

    Without `--json`, prints a one-line summary. With `--json`, emits the
    full `SprintFile` as JSON — useful for piping into `jq` or another
    consumer that wants to introspect a sprint's parsed state.
    """
    from cp_engine.sprints import parse_sprint_file, sprint_file_to_dict

    sf = parse_sprint_file(path)
    if as_json:
        import json

        click.echo(json.dumps(sprint_file_to_dict(sf), default=str, indent=2))
    else:
        click.echo(
            f"{sf.project_code} · {sf.week_iso} · "
            f"{len(sf.client_open_asks)} asks · {len(sf.risks)} risks"
        )


@main.command("parse-transcript")
@click.argument("path", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option(
    "--gap-threshold",
    type=int,
    default=2,
    help="Flag audio gaps >= this many minutes. Default 2.",
)
@click.option(
    "--codes",
    default="",
    help="Comma-separated project codes to scan for. Empty → no code scan.",
)
def parse_transcript_cmd(path: Path, gap_threshold: int, codes: str) -> None:
    """Audit a Fathom-style transcript. Emits JSON to stdout.

    Output schema:
      {speakers, duration_minutes, gaps[], mentioned_codes[], action_items[]}

    Used by /cp-ingest plugin to surface a confirmation prompt before
    writing anything. Catches transcripts with audio gaps, missing speakers,
    or no mentioned project codes — the W19 retro flagged these failure
    modes after several got into committed artifacts.
    """
    import json
    from cp_engine.ingest import parse_transcript

    code_list = tuple(c.strip() for c in codes.split(",") if c.strip())
    audit = parse_transcript(
        path, gap_threshold_minutes=gap_threshold, project_codes=code_list
    )
    click.echo(json.dumps(audit.to_dict(), indent=2))


@main.command("list-active-projects")
@click.option(
    "--scope",
    type=click.Choice(["1p", "fpsf", "canonic", "all"]),
    default="all",
    help="Filter by scope. Default 'all'.",
)
@click.option(
    "--company",
    default=None,
    help="Filter by company code (case-insensitive, e.g. 'GGL' or 'IBX'). "
    "Used by /cp-ingest --account <company> to find the projects a "
    "multi-project account meeting touches. Default: all companies.",
)
def list_active_projects_cmd(scope: str, company: str | None) -> None:
    """List active projects from MC-2 as JSON for transcript classification.

    Output: list of {code, name, company_code, company_name, owner, scope}.
    Used by /cp-ingest plugin to give Claude the candidate-projects list
    when classifying which projects a transcript touches.
    """
    import json
    from cp_engine.state import scope_for
    from cp_engine.status import is_active_status
    from cp_engine.sync import _default_backend_factory

    config = _load_config_or_die()
    backend = _default_backend_factory(config.sync.backend)
    projects = backend.read_projects(config)

    company_lc = company.lower() if company else None

    out = []
    for p in projects:
        if p.source == "engagement":
            if not is_active_status(p.status) or p.is_internal:
                continue
        else:
            if p.status != "Active":
                continue
        proj_scope = scope_for(p.company_kind)
        if scope != "all" and proj_scope != scope:
            continue
        # Phase B.2: --company filter for /cp-ingest --account flow.
        if company_lc and (p.company_code or "").lower() != company_lc:
            continue
        out.append(
            {
                "code": p.code,
                "name": p.name,
                "company_code": p.company_code,
                "company_name": p.company_name,
                "owner": p.owner,
                "scope": proj_scope,
                "source": p.source,
            }
        )
    out.sort(key=lambda r: (r["scope"], r["code"]))
    click.echo(json.dumps(out, indent=2))


@main.command("ingest")
@click.option(
    "--plan",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    required=True,
    help="YAML plan file to execute.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Validate the plan and print what would happen, but don't write files.",
)
def ingest_cmd(plan: Path, dry_run: bool) -> None:
    """Execute an ingest plan against the cp tenant.

    The plan is a YAML file produced by /cp-ingest (or hand-authored).
    Schema: {transcript: ..., projects: {<code>: {<verb>: [items]}}, themes: [...]}

    On success: writes bullets to the right sprint-file subsections; the
    plan is saved (separately, by the plugin) to sprints/<W##>/_ingest-log/
    for audit. Idempotent — re-running the same plan is a no-op via
    content-hash deduplication.
    """
    import json
    import yaml
    from cp_engine.ingest import execute_plan, IngestPlanError

    plan_data = yaml.safe_load(plan.read_text(encoding="utf-8"))
    config = _load_config_or_die()
    today = datetime.now().date()

    if dry_run:
        # Just validate the plan; report what would happen.
        from cp_engine.ingest import _validate_plan, _normalize_verb
        try:
            _validate_plan(plan_data)
        except IngestPlanError as exc:
            click.echo(f"Plan validation failed: {exc}", err=True)
            sys.exit(1)
        projects = plan_data.get("projects") or {}
        themes = plan_data.get("themes") or []
        summary = {
            "valid": True,
            "projects_touched": list(projects.keys()),
            "verb_counts": {
                code: {_normalize_verb(v): len(items) for v, items in entries.items()}
                for code, entries in projects.items()
            },
            "themes_count": len(themes),
        }
        click.echo(json.dumps(summary, indent=2))
        return

    try:
        result = execute_plan(plan_data, tenant_root=config.root, today=today)
    except IngestPlanError as exc:
        click.echo(f"Plan validation failed: {exc}", err=True)
        sys.exit(1)

    click.echo(json.dumps(result.to_dict(), indent=2))
    if result.errors:
        sys.exit(2)


@main.command("write-region")
@click.argument("file", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.argument("region")
@click.option("--body", help="New body content for the region.")
@click.option(
    "--body-file",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    help="Read body from a file instead.",
)
def write_region_cmd(
    file: Path, region: str, body: str | None, body_file: Path | None
) -> None:
    """Splice content into an engine-managed region (escape hatch).

    Usage:
      cp write-region 1p/ggl-5168-activation/cp.md inbound-strip --body-file new.md

    Logs a warning so this is visible when used. Routine writes should
    go through `cp ingest` or its structured verbs, not through this.
    """
    import logging
    from cp_engine.render import splice_managed_region

    if body is None and body_file is None:
        click.echo("Provide --body or --body-file.", err=True)
        sys.exit(1)
    new_body = body if body is not None else body_file.read_text(encoding="utf-8")

    logger = logging.getLogger("cp_engine.cli")
    logger.warning(
        "write-region called directly on %s region %r — routine writes "
        "should go through `cp ingest`. Using this is fine but visible.",
        file, region,
    )

    existing = file.read_text(encoding="utf-8")
    updated = splice_managed_region(existing, region, new_body)
    if updated != existing:
        file.write_text(updated)
        click.echo(f"wrote {file}")
    else:
        click.echo("no change")


@main.command("fathom-list")
@click.option(
    "--since",
    "since_iso",
    default=None,
    help="ISO timestamp; only return meetings newer than this. Default: most recent.",
)
@click.option("--limit", type=int, default=50, help="Max rows to return. Default 50.")
@click.option(
    "--type",
    "meeting_type",
    type=click.Choice([
        "project-status", "account-status", "sprint-planning",
        "work-session", "1-1", "untagged",
    ]),
    default=None,
    help="Filter by meeting_type (Phase B). Used by /cp-ingest --account to "
    "pull just account-status meetings. Default: no filter.",
)
def fathom_list_cmd(since_iso: str | None, limit: int, meeting_type: str | None) -> None:
    """List Fathom meetings from Supabase, newest first.

    Reads from `fathom_meetings` (the same Supabase project MC-2 uses;
    populated by the fathom-meeting-sync webhook). Lightweight rows —
    use `cp fathom-fetch <id>` to pull a full transcript.
    """
    import json
    from cp_engine.fathom import list_meetings

    config = _load_config_or_die()
    meetings = list_meetings(
        config, since_iso=since_iso, limit=limit, meeting_type=meeting_type
    )
    click.echo(json.dumps([m.to_dict() for m in meetings], indent=2))


@main.command("fathom-fetch")
@click.argument("meeting_id")
@click.option(
    "--needs-review",
    is_flag=True,
    help="Stage to transcripts/needs-review/ instead of transcripts/incoming/. "
    "Used by auto-poll when the confidence gate trips.",
)
def fathom_fetch_cmd(meeting_id: str, needs_review: bool) -> None:
    """Fetch a Fathom meeting from Supabase and stage its transcript to disk.

    Default location: `transcripts/incoming/<meeting-id>.txt` at the
    tenant root. Pass `--needs-review` to stage to needs-review/ instead.

    Output is JSON: `{path, meeting_id, title, project_tags, ...}`.
    Hand the path to /cp-ingest to deepen.
    """
    import json
    from cp_engine.fathom import fetch_meeting, stage_transcript

    config = _load_config_or_die()
    meeting = fetch_meeting(config, meeting_id)
    path = stage_transcript(meeting, tenant_root=config.root, needs_review=needs_review)
    click.echo(
        json.dumps(
            {
                "path": str(path),
                "meeting_id": meeting.id,
                "title": meeting.title,
                "meeting_date": meeting.meeting_date,
                "project_tags": meeting.project_tags,
                "duration_minutes": meeting.duration_minutes,
                "needs_review": needs_review,
            },
            indent=2,
        )
    )


@main.command("fathom-auto-poll")
@click.option(
    "--limit",
    type=int,
    default=20,
    help="Max meetings to consider per poll. Default 20.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="List what would be staged + classified, but don't write files.",
)
def fathom_auto_poll_cmd(limit: int, dry_run: bool) -> None:
    """Poll Fathom Supabase for new meetings and stage them.

    Confidence gate: meetings with non-empty + non-`untagged` `project_tags`
    are staged to `transcripts/incoming/` for /cp-ingest. Meetings with no
    real tags go to `transcripts/needs-review/` for manual handling.

    State (last_polled_at + processed_ids) at `.cp-engine/state.json`
    (gitignored). Idempotent — already-processed ids are skipped.

    Output: JSON summary `{polled, staged_for_ingest[], staged_for_review[],
    skipped_already_processed[], errors[]}`.

    The `[fathom-ingest]` GitHub Actions workflow runs this on a cron and
    commits the staged files (not the deepening — /cp-ingest still requires
    /cp-ingest plugin orchestration which has Claude as the planner).
    """
    import json
    from cp_engine.fathom import (
        list_meetings,
        fetch_meeting,
        stage_transcript,
        has_good_tags,
        load_state,
        save_state,
        already_processed,
        mark_processed,
    )

    config = _load_config_or_die()
    state = load_state(config.root)
    meetings = list_meetings(config, since_iso=state.last_polled_at, limit=limit)

    summary: dict = {
        "polled": len(meetings),
        "staged_for_ingest": [],
        "staged_for_review": [],
        "skipped_already_processed": [],
        "errors": [],
    }

    for m in meetings:
        if already_processed(state, m.id):
            summary["skipped_already_processed"].append(m.id)
            continue
        try:
            target = "ingest" if has_good_tags(m.project_tags) else "review"
            if dry_run:
                bucket = "staged_for_ingest" if target == "ingest" else "staged_for_review"
                summary[bucket].append({"id": m.id, "title": m.title, "tags": m.project_tags})
                continue
            full = fetch_meeting(config, m.id)
            path = stage_transcript(
                full,
                tenant_root=config.root,
                needs_review=(target == "review"),
            )
            bucket = "staged_for_ingest" if target == "ingest" else "staged_for_review"
            summary[bucket].append(
                {"id": m.id, "title": m.title, "path": str(path), "tags": m.project_tags}
            )
            state = mark_processed(state, m.id)
        except Exception as exc:
            summary["errors"].append({"id": m.id, "error": str(exc)})

    if not dry_run:
        save_state(state, config.root)

    click.echo(json.dumps(summary, indent=2))


@main.command("prep-agenda")
@click.option(
    "--projects",
    "project_filter",
    default="",
    help="Comma-separated project codes to scope the agenda to. "
    "Empty (default) → full sprint planning across all active projects.",
)
@click.option(
    "--out",
    type=click.Path(dir_okay=False, path_type=Path),
    default=None,
    help="Write the agenda to this file path. Defaults to stdout.",
)
@click.option(
    "--summary",
    is_flag=True,
    help="Emit JSON metrics (workload by owner, coverage, urgency counts) "
    "instead of the rendered markdown. The /cp-prep plugin uses this.",
)
@click.option(
    "--no-sync",
    is_flag=True,
    help="Skip the automatic sync-if-stale check at the start. "
    "By default, prep-agenda auto-runs `cp sync` if master-cp's last sync "
    "is more than 10 minutes old, so the agenda never shows stale data.",
)
def prep_agenda_cmd(
    project_filter: str, out: Path | None, summary: bool, no_sync: bool
) -> None:
    """Render a sprint-planning agenda from current cp tenant state.

    Reads master-cp's project list, weekly-cp.md decisions, current-week
    sprint files, and per-project cp.md Quick Resume sections; cross-
    references everything into project-grouped blocks.

    Default: agenda for all active projects (full sprint planning).
    With `--projects <code>,<code>...`: scoped agenda for those projects only.

    Output is markdown. Default to stdout; pass `--out sprints/<W##>/_agenda.md`
    to overwrite the per-week agenda file. Pass `--summary` to emit JSON
    metrics instead (used by the /cp-prep plugin command).
    """
    import json
    from datetime import datetime, timedelta
    from cp_engine.agenda import build_agenda, build_agenda_summary, is_sync_stale
    from cp_engine.sync import _default_backend_factory, sync_tenant

    config = _load_config_or_die()

    # v0.8.8.2: auto-sync if stale. Avoids the "agenda shows yesterday's
    # owner data" footgun. Opt-out via --no-sync for environments where
    # the network round-trip isn't acceptable (CI dry-runs, etc.).
    if not no_sync and is_sync_stale(config):
        click.echo("master-cp sync is stale; running cp sync first…", err=True)
        try:
            sync_tenant(config)
        except Exception as exc:
            click.echo(f"sync failed (continuing with stale data): {exc}", err=True)

    backend = _default_backend_factory(config.sync.backend)
    projects = backend.read_projects(config)

    # Pull last-week allocations the same way master-cp does, so the agenda's
    # per-project "last sprint hours" line matches what's in master-cp.md.
    today = datetime.now().date()
    last_monday = today - timedelta(days=today.weekday() + 7)
    try:
        allocations = backend.read_allocations(config, last_monday.isoformat())
    except Exception:
        allocations = None

    last_sprint_hours_by_project: dict[str, str] = {}
    if allocations and getattr(allocations, "by_project", None):
        for code, alloc in allocations.by_project.items():
            entries = [f"{e.person_name.split()[0]} {e.hours:g}h" for e in alloc.entries]
            if entries:
                last_sprint_hours_by_project[code] = ", ".join(entries)

    code_filter = tuple(c.strip() for c in project_filter.split(",") if c.strip()) or None

    if summary:
        s = build_agenda_summary(
            config,
            tuple(projects),
            today=today,
            project_filter=code_filter,
            last_sprint_hours_by_project=last_sprint_hours_by_project,
        )
        click.echo(json.dumps(s.to_dict(), indent=2))
        return

    agenda_md = build_agenda(
        config,
        tuple(projects),
        today=today,
        project_filter=code_filter,
        last_sprint_hours_by_project=last_sprint_hours_by_project,
    )

    if out:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(agenda_md)
        click.echo(f"wrote {out}")
    else:
        click.echo(agenda_md)


def _load_config_or_die() -> "TenantConfig":  # noqa: F821
    """Load tenant config from cwd; exit with a friendly error on failure."""
    try:
        return load(Path.cwd())
    except CommittedConfigMissing:
        click.echo(
            "No .cp-engine.toml in this directory. Run `cp init` "
            "or cd into the cp tenant root.",
            err=True,
        )
        sys.exit(1)
    except ConfigError as exc:
        click.echo(f"Config error: {exc}", err=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
