"""`cp merge-check` — prove a merge didn't silently drop tracked content.

The tenant convention is to resolve generated files (sprint scaffolds,
`_sources.md`, spine mirrors) `--ours` on a conflict, because sync regenerates
them anyway. That is right *only when your side is genuinely newer*. When the
auto-ingest webhook has been writing to the remote while a session works
locally, `--ours` throws that content away — and a silent content drop looks
exactly like a clean resolution. Nothing errors; the merge commits; the bullets
are simply gone.

The cheap proof is a set-difference on `cp:hash` markers, the 8-hex content
hashes auto-ingest stamps on every bullet it writes. Enumerate the hashes
present on a reference commit's version of each file, then assert every one
still appears somewhere in the working tree. A hash that vanished is content
that vanished.

Real case (2026-08-19): merging 19 remote commits produced add/add conflicts
on 39 W35 scaffold files. Blanket `--ours` would have dropped seven
auto-ingest bullets — including an ESCALATED resourcing risk on storyos —
with no error and no visible sign.

Deliberately NOT limited to the files git reports as conflicted: a bad
`checkout --ours`, an over-eager `git restore`, or a hand-resolution that
truncated a section all lose content the same way, and all are caught by the
same check.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

# The content-hash marker auto-ingest stamps on bullets it writes:
#   ... text <!-- cp:hash=8f3a1c2b -->
_HASH_RE = re.compile(r"cp:hash=(?P<hash>[0-9a-f]{8})")

# An engine-managed region. Its content is a PROJECTION — of MC-2 (open-asks,
# inbound-strip) or of other sprint files (carry-forward, the master-cp
# roll-ups) — regenerated by sync, so a hash leaving one is not loss. The
# authored `exec-summary` region counts too: sync owns its shape, and the
# tenant tree carried no hashes in it (0 across 53 regions, 2026-10-01).
# 2026-10-01: a merge reported 35 "MISSING" bullets, every one of them inside
# a region like these, and none was lost.
_MANAGED_REGION_RE = re.compile(
    r"<!-- cp-engine:start (?P<name>[\w-]+) -->.*?<!-- cp-engine:end (?P=name) -->",
    re.S,
)

# Files worth checking: markdown carrying ingest-written bullets. Binary and
# cache files never carry cp:hash markers, so scanning them is wasted work.
_CHECKED_SUFFIXES = (".md",)


class MergeCheckError(RuntimeError):
    """The check could not read the reference commit — so it cannot prove
    nothing was lost, and must not report "no content lost" (step 3)."""


@dataclass(frozen=True)
class LostContent:
    """One `cp:hash` present on the reference commit but missing from the tree.

    `path` is repo-relative. `snippet` is the bullet as the reference commit
    had it, trimmed for display — enough to recognize what would be lost and
    to recover it by hand if needed.
    """

    path: str
    hash: str
    snippet: str


def _git(args: list[str], cwd: Path) -> str:
    """Run a git command, returning stdout ('' on failure).

    Failures are swallowed deliberately: a file that doesn't exist on the
    reference commit (a genuinely new local file) is the normal case, not an
    error, and it has nothing to lose.
    """
    try:
        out = subprocess.run(
            ["git", *args],
            cwd=cwd,
            capture_output=True,
            text=True,
            check=False,
        )
        return out.stdout if out.returncode == 0 else ""
    except OSError:
        return ""


def _git_show_checked(ref: str, rel: str, cwd: Path) -> str:
    """`git show ref:rel` for a path `ls-tree` just listed — so it EXISTS on
    the ref, and a failure is a real failure, not the new-file case `_git`
    swallows. Raises MergeCheckError."""
    try:
        out = subprocess.run(
            ["git", "show", f"{ref}:{rel}"],
            cwd=cwd,
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as exc:
        raise MergeCheckError(f"git show {ref}:{rel} failed: {exc}") from exc
    if out.returncode != 0:
        raise MergeCheckError(
            f"git show {ref}:{rel} exited {out.returncode}: "
            f"{(out.stderr or '').strip()[:200]}"
        )
    return out.stdout


def _hashes_with_context(body: str) -> dict[str, str]:
    """Map every cp:hash in `body` OUTSIDE a managed region to the line
    carrying it. Hand-written content is what must survive a merge; an
    unterminated start marker matches nothing, so its content stays checked."""
    found: dict[str, str] = {}
    for line in _MANAGED_REGION_RE.sub("", body).splitlines():
        for m in _HASH_RE.finditer(line):
            found.setdefault(m.group("hash"), line.strip())
    return found


def check_merge(
    repo_root: Path,
    ref: str = "ORIG_HEAD",
) -> tuple[list[LostContent], int]:
    """Compare `ref`'s cp:hash markers against the working tree.

    Returns (lost, files_checked). `ref` defaults to ORIG_HEAD, which git sets
    to the pre-merge HEAD — but the interesting comparison after resolving
    `--ours` is usually against the REMOTE side, so callers typically pass
    `origin/main` or `MERGE_HEAD`.

    Only hashes OUTSIDE engine-managed regions on `ref` are required to
    survive: a region's content is regenerated by sync, so its hashes are
    projections, not the content itself.

    A hash is considered present if it appears anywhere in the same file in
    the working tree; position and surrounding edits don't matter, only that
    the content survived. A file deleted locally but present on `ref` reports
    all of its hashes as lost, which is the correct reading — deleting a file
    full of ingest bullets is exactly the accident this catches.
    """
    listing = _git(["ls-tree", "-r", "--name-only", ref], repo_root)
    lost: list[LostContent] = []
    checked = 0

    for rel in listing.splitlines():
        rel = rel.strip()
        if not rel or not rel.endswith(_CHECKED_SUFFIXES):
            continue

        # Listed by ls-tree, so it exists on `ref`: a failed read here would
        # otherwise skip the file and report "no content lost" (step 3).
        ref_body = _git_show_checked(ref, rel, repo_root)
        if not ref_body:
            continue
        ref_hashes = _hashes_with_context(ref_body)
        if not ref_hashes:
            continue

        checked += 1
        local = repo_root / rel
        local_body = local.read_text(encoding="utf-8") if local.is_file() else ""
        local_hashes = set(_HASH_RE.findall(local_body))

        for h, snippet in ref_hashes.items():
            if h not in local_hashes:
                lost.append(
                    LostContent(
                        path=rel,
                        hash=h,
                        snippet=snippet[:160],
                    )
                )

    return lost, checked


def commits_behind_upstream(repo_root: Path) -> tuple[str, int] | None:
    """(upstream name, commits HEAD is behind it), or None when unknowable.

    WHY SYNC ASKS THIS (#310). The auto-ingest webhook pushes bullets straight
    to the tenant's remote. A `cxp sync` on a clone that has not pulled them
    renders sprint files and roll-ups from a tree missing the webhook's newest
    content — and the merge that follows is exactly where a blanket `--ours`
    (or a rebase `--theirs`) then drops them. 2026-09-22: a sync one fetch
    behind, then a rebase, lost 18 bullets.

    Reads the remote-tracking ref only — NO fetch, since sync has never
    touched the network for git and a warning should not add a network
    dependency. So the count is "as of your last fetch": a zero here does not
    prove the clone is current, a non-zero proves it is not.

    None when there is no upstream (detached HEAD, a local-only branch, not a
    git repo) — there is nothing to compare against, which is not a warning.
    """
    upstream = _git(
        ["rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}"], repo_root
    ).strip()
    if not upstream:
        return None
    count = _git(["rev-list", "--count", "HEAD..@{u}"], repo_root).strip()
    try:
        return upstream, int(count)
    except ValueError:
        return None
