"""Re-scaffold pristine project CPs from the current template.

A project CP is "pristine" if it still contains the scaffold's placeholder
text. Pristine CPs were generated by an older engine version and may have
outdated provenance, missing metadata blocks, or wrong section structures.

Edited CPs (placeholder gone or any section filled in) are NEVER touched —
hand-written content is sacred per the engine's scaffold-once design.

Use case: after upgrading cp-engine, run `cp refresh-pristine` to update
the template shape across the tenant before anyone has hand-edited CPs.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from cp_engine.config import TenantConfig
from cp_engine.render import render_project_cp
from cp_engine.sync import _default_backend_factory
from cp_engine.state import ProjectState

# The exact placeholder string that v0.1 + v0.2 templates inject for the
# one-line description. Presence == "this CP has never been edited."
# Intentionally specific so we don't false-positive on something a human
# happened to write.
_PRISTINE_MARKER = "_<one-line description of what this project is and who it's for>_"


@dataclass(frozen=True)
class RefreshResult:
    """Outcome of one refresh-pristine run."""

    pristine_files: tuple[Path, ...]  # files that were refreshed (or would be in dry-run)
    skipped_files: tuple[Path, ...]   # files left alone because they had hand-written content


def refresh_pristine_cps(config: TenantConfig, *, dry_run: bool = False) -> RefreshResult:
    """Re-scaffold every pristine project CP using the current template.

    Reads the source-of-truth state via the same backend `cp sync` uses,
    so the regenerated CPs reflect current MC-2 data (status, owner, etc.)
    not whatever was true when the CP was originally scaffolded.
    """
    projects_dir = config.root / "projects"
    if not projects_dir.is_dir():
        return RefreshResult(pristine_files=(), skipped_files=())

    # Read current source-of-truth state so the regenerated CPs reflect
    # today's data, not whatever was in MC-2 when they were first scaffolded.
    backend = _default_backend_factory(config.sync.backend)
    states_by_code = {p.code: p for p in backend.read_projects(config)}

    pristine: list[Path] = []
    skipped: list[Path] = []

    for path in sorted(projects_dir.iterdir()):
        if path.is_dir():
            continue  # skip projects/archived/ subdir
        if path.suffix != ".md":
            continue

        contents = path.read_text()
        if _PRISTINE_MARKER not in contents:
            skipped.append(path)
            continue

        # Pristine. If the project still exists in source-of-truth, regenerate
        # using current data. If it doesn't (project was archived/removed
        # between scaffold and now), leave it alone — refresh is for template
        # updates, not for cleanup. The archive sweep in sync handles cleanup.
        code = path.stem
        state = states_by_code.get(code)
        if state is None:
            skipped.append(path)
            continue

        if not dry_run:
            new_body = render_project_cp(config, state, tracked_issues=())
            path.write_text(new_body)
        pristine.append(path)

    return RefreshResult(
        pristine_files=tuple(pristine),
        skipped_files=tuple(skipped),
    )
