"""An account summary must never be appended inside a cp-engine managed region.

THE REPORT (2026-09-15). `_write_account_summary` appends its bullet before the
next `^## ` heading after `## Account summaries`. That is only the end of the
handwritten zone when no managed region intervenes — and in the cp tenant it
does not hold: the next heading is

    <!-- cp-engine:start themes-strip -->
    ## Themes (auto-aggregated from sprints/<W##>/_week.md, last 2 weeks)

so the bullet landed BETWEEN the marker and its heading, inside cp-engine's own
derived territory. The write succeeded, the commit was real, and the next
`cp sync` regenerated the strip and deleted the paragraph.

WHAT IT COST. Measured across the tenant's history on 2026-09-15: of 52 account
summaries ever written to `weekly-cp.md`, 3 were still on disk. 39 were removed
by `[cp-sync]` commits across 18 separate runs since 2026-07-08, and in every
one of those 18 the number removed equalled exactly the number of bullets
sitting after the first marker in the parent commit — no exceptions. Each lost
paragraph had cost a model call over a full meeting transcript.

WHY IT HID. Every angle looked healthy: the ingest reported success, sync was
doing precisely its job regenerating a region it owns, the deletion rode inside
a `[cp-sync]` commit carrying legitimate churn so no diff read as a loss, and an
account summary is a paragraph nobody is waiting for — unlike a per-project
bullet, nobody opens `weekly-cp.md` hunting for the W31 TEL entry, so absence
never surfaced as a complaint.

These tests pin the clamp. The first one FAILS against the pre-fix code.
"""

from __future__ import annotations

from cp_engine.ingest import _write_account_summary

# The real shape from the cp tenant: the next `## ` after the section heading
# lives inside a managed region.
TENANT_SHAPE = """\
# Weekly CP

## Account summaries

- [2026-W20 · GGL] An older summary that predates this bug.

<!-- cp-engine:start themes-strip -->
## Themes (auto-aggregated from sprints/<W##>/_week.md, last 2 weeks)

- _No themes captured in the last 2 weeks._
<!-- cp-engine:end themes-strip -->
"""


def _item(text="A two-person working session.", company="canonic-internal"):
    return {"text": text, "company": company, "week": "2026-W38"}


def _marker_zone(body: str) -> str:
    """Everything a `cp sync` would regenerate and therefore discard."""
    start = body.index("<!-- cp-engine:start themes-strip -->")
    end = body.index("<!-- cp-engine:end themes-strip -->")
    return body[start:end]


class TestTheReportedLoss:
    def test_bullet_does_not_land_inside_the_managed_region(self, tmp_path):
        """The exact failure of 2026-09-15 — dc24e2ba written, 6f2dc74b ate it."""
        p = tmp_path / "weekly-cp.md"
        p.write_text(TENANT_SHAPE, encoding="utf-8")

        assert _write_account_summary(_item(), p) is True

        body = p.read_text(encoding="utf-8")
        assert "CANONIC-INTERNAL" in body, "the bullet was not written at all"
        assert "CANONIC-INTERNAL" not in _marker_zone(body), (
            "bullet landed inside the themes-strip managed region — the next "
            "`cp sync` would regenerate the strip and silently delete it"
        )

    def test_bullet_survives_a_regeneration_of_the_managed_region(self, tmp_path):
        """The far side of the boundary: simulate what sync actually does.

        Writing and reading back in the same place proves persistence, not
        survival. What matters is whether the bullet is still there after the
        region it may have landed in is rebuilt.
        """
        p = tmp_path / "weekly-cp.md"
        p.write_text(TENANT_SHAPE, encoding="utf-8")
        _write_account_summary(_item(), p)

        body = p.read_text(encoding="utf-8")
        start = body.index("<!-- cp-engine:start themes-strip -->")
        end = body.index("<!-- cp-engine:end themes-strip -->")
        regenerated = (
            body[:start]
            + "<!-- cp-engine:start themes-strip -->\n"
            + "## Themes (auto-aggregated from sprints/<W##>/_week.md, last 2 weeks)\n\n"
            + "- _Regenerated by sync._\n"
            + body[end:]
        )

        assert "CANONIC-INTERNAL" in regenerated, (
            "the summary did not survive a regeneration of the managed region"
        )

    def test_bullet_lands_under_the_section_not_before_it(self, tmp_path):
        """Clamping must not push the bullet above its own heading."""
        p = tmp_path / "weekly-cp.md"
        p.write_text(TENANT_SHAPE, encoding="utf-8")
        _write_account_summary(_item(), p)

        body = p.read_text(encoding="utf-8")
        assert body.index("## Account summaries") < body.index("CANONIC-INTERNAL")

    def test_existing_bullets_are_preserved(self, tmp_path):
        p = tmp_path / "weekly-cp.md"
        p.write_text(TENANT_SHAPE, encoding="utf-8")
        _write_account_summary(_item(), p)

        body = p.read_text(encoding="utf-8")
        assert "[2026-W20 · GGL]" in body
        assert "_No themes captured in the last 2 weeks._" in body


class TestShapesWithoutTheHazard:
    """The clamp must not change behaviour where no marker intervenes."""

    def test_plain_section_followed_by_a_normal_heading(self, tmp_path):
        body = (
            "# Weekly CP\n\n## Account summaries\n\n"
            "- [2026-W20 · GGL] Older.\n\n"
            "## Active research\n\n- something\n"
        )
        p = tmp_path / "weekly-cp.md"
        p.write_text(body, encoding="utf-8")

        assert _write_account_summary(_item(), p) is True
        out = p.read_text(encoding="utf-8")
        assert out.index("CANONIC-INTERNAL") < out.index("## Active research")
        assert out.index("[2026-W20 · GGL]") < out.index("CANONIC-INTERNAL")

    def test_section_at_end_of_file(self, tmp_path):
        body = "# Weekly CP\n\n## Account summaries\n\n- [2026-W20 · GGL] Older.\n"
        p = tmp_path / "weekly-cp.md"
        p.write_text(body, encoding="utf-8")

        assert _write_account_summary(_item(), p) is True
        assert "CANONIC-INTERNAL" in p.read_text(encoding="utf-8")

    def test_marker_before_the_section_is_not_a_clamp(self, tmp_path):
        """Only a marker AFTER the section start bounds the insert."""
        body = (
            "# Weekly CP\n\n"
            "<!-- cp-engine:start decisions-strip -->\n"
            "## Decisions\n\n- a decision\n"
            "<!-- cp-engine:end decisions-strip -->\n\n"
            "## Account summaries\n\n- [2026-W20 · GGL] Older.\n"
        )
        p = tmp_path / "weekly-cp.md"
        p.write_text(body, encoding="utf-8")

        assert _write_account_summary(_item(), p) is True
        out = p.read_text(encoding="utf-8")
        assert out.index("## Account summaries") < out.index("CANONIC-INTERNAL")
        assert "- a decision" in out


class TestIdempotency:
    def test_rewriting_the_same_summary_is_a_no_op(self, tmp_path):
        p = tmp_path / "weekly-cp.md"
        p.write_text(TENANT_SHAPE, encoding="utf-8")

        assert _write_account_summary(_item(), p) is True
        once = p.read_text(encoding="utf-8")
        assert _write_account_summary(_item(), p) is False
        assert p.read_text(encoding="utf-8") == once
